### ISSUE TITLE
Windows: Game fails to read/write certain files if Controlled Folder Access is enabled

### ISSUE THREAD

**Issue by KabanFriends** [TerryCavanagh/VVVVVV#1010]
In Windows Defender (Windows 10 or 11), if "Controlled Folder Access" is enabled, the game fails to:
- Create `C:\Users\[user]\Documents\VVVVVV` folder if it's missing
- Read/write certain files including `settings.vvv`, `levelstats.vvv` and more

From what I tested, this issue does *not* occur when VVVVVV is launched from where Steam installs `VVVVVV.exe`, (most likely because apps installed by steam are given special permissions) but might be wrong depending on users' PC configurations.
I am also not sure if Controlled Folder Access is enabled by default or not.

Reproduction:
1. Enable [Controlled Folder Access](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-controlled-folders?view=o365-worldwide) (Windows Security > Virus & threat protection > Ransomware protection > Controlled folder access)
2. Delete `C:\Users\[user]\Documents\VVVVVV` folder if it already exists
3. Launch VVVVVV
4. Observe that the game does not start
- You can see different read/write issue by creating VVVVVV folder manually (settings & save files don't work)

**Comment by flibitijibibo** [comment]
We may need to take notes from SDL here; I _think_ SDL_GetPrefPath makes this clearer but since we have the backward compatibility concern our Windows path likely doesn't cover this yet.

**Comment by Dav999-v** [comment]
We specifically use PHYSFS_getPrefDir on all OSes except Windows, so that we can use `Documents\VVVVVV` instead of an AppData path. (apparently PHYSFS_getPrefDir and SDL_GetPrefPath are pretty much the same thing, wow those documentations look similar)

Ally said on Discord that Controlled Folder Access is not enabled by default though, so this is probably not the start of an apocalypse of players not being able to save anything.

**Comment by leo60228** [comment]
My understanding is that Controlled Folder Access is primarily an enterprise feature that requires administrators to explicitly approve *any* programs trying to write to default folders. In this light, I'm not really sure that this qualifies as an issue with VVVVVV, though maybe it should fall back to AppData if it doesn't have permissions for Documents.

**Comment by Dav999-v** [comment]
I think the biggest issue is that the game just silently fails to start if it can't mount the base dir. (It prints something to console, but y'know.) So if we made the game display a message box with an explanation in this case ("check that Controlled Folder Access is disabled"), that'd already be a very good step I think.

**Comment by flibitijibibo** [comment]
SDL pretty much does exactly that, so let's just log it and bail: https://github.com/libsdl-org/SDL/blob/main/src/filesystem/windows/SDL_sysfilesystem.c#L156

For failures this early we might be able to use SDL_ShowSimpleMessageBox if we're worried that the error will be too hard to identify (i.e. no log files available).

**Comment by Dav999-v** [comment]
It could be like the missing data.zip messagebox; right now the game apparently fails to start because of a bail.

**Comment by InfoTeddy** [comment]
Reopening this issue because a [recent Steam discussion thread](https://steamcommunity.com/app/70300/discussions/0/4139438760457995957/) lead to some discussion on the Discord server and a little more research. It turns out that the setting for Controlled Folder Access is stored in the Windows registry, so we could detect it and we might even be able to disable it or whitelist ourselves. Either possibility provides a better user experience and more information than just a generic "cannot save" error.

We should...

- [ ] Detect when CFA is enabled and blocks us from writing (I tested it and every write will fail with a generic "file not found" error).
- [ ] Tell the user to disable CFA or whitelist us.
- [ ] See if it's possible to disable CFA or whitelist us ourselves (maybe through a Windows prompt for administrative privileges).
- [ ] If the filesystem can't be initialized (because we can't create the base folder) but we still have `data.zip`, show the above message in-game instead of in a separate `SDL_ShowSimpleMessageBox` dialog box.

**Comment by Daaaav** [comment]
Found out there are URI schemes for the Windows Security app, so it's probably the cleanest to tell the user to disable CFA or whitelist us, and then have a button [ OPEN SETTINGS ] that brings them straight to the setting:

- `windowsdefender://ransomwareprotection/`: the main "ransomware" page, which has the big CFA on/off switch first and foremost (no UAC prompt to go to this page, but you get a UAC prompt if you toggle the setting)
- `windowsdefender://allowappthroughfolder/`: "Allow an app through Controlled Folder Access" page, so users can easily whitelist us (this URI immediately gives a UAC prompt)
- `windowsdefender://protectedfolders/` (for completeness): the protected folders, not really useful

**Comment by InfoTeddy** [comment]
> We should...

Actually, nevermind. After some discussion in the Discord, we decided not to. Reason being that we figured some aggressive antiviruses might get suspicious if we tried to read from the Windows Registry after getting blocked.

Furthermore, when we do get blocked, a notification will pop up in the corner telling the user that Controlled Folder Access blocked VVVVVV. I don't know if that's reliable but it's good enough for me to indicate to the user that CFA is the problem and they should fix it.

I also just am not motivated enough to deal with the slog that is writing Windows Registry code.
