### ISSUE TITLE
A few suggestions for the Italian translators

### ISSUE THREAD

**Issue by ffaf1** [TerryCavanagh/VVVVVV#1060]
A few notes for the Italian translators. Italian follows.

---

Innanzitutto grandissimi complimenti, avete fatto un ottimo lavoro, la traduzione è concreta, precisa, in italiano — cosa non scontata ultimamente — e con delle soluzioni riuscitissime!

Detto questo, qualche nota che ho preso mentre giocavo. Vogliono solo essere uno spunto di riflessione:

- **Ora segui me** Preferirei «ora seguimi» (visto che nella stanza dopo c’è «ora stammi vicino»).
- **Coraggio, giovane**, magari «Coraggio, giovanotto».
- **Cosa? Non ho capito niente!**, forse è meglio «Cosa? Non ci ho capito niente!», il *ci* — pronome? boh — è un po’ più spontaneo nel dialogo e indica meglio che l’interlocutore sta sbroccando.
- **È una gioia riavere Victoria con noi** Vedo che due personaggi usano questa locuzione, Victoria e il rosso. Che Victoria la usi può essere considerato un vezzo suo, ma Vermillion semplicemente può dire «È bellissimo che…», «È fantastico che…», «Che bello che…» o se proprio si vuole mantenere «Che gioia riavere Victoria con noi!».
  In generale vedo «gioia» usato frequentemente come traducente di varie espressione (p.es. «You are ok!»). Non è sbagliato per carità però salta all’occhio perché appunto è frequente ed in bocca a quasi tutti i personaggi. Io limiterei ad uno e gli altri che se la cavino con «Benritrovato, Capitano!» «Sono felicissimo di esser qui» etc.
- **Registro personale**: mhhhhhh non so se «Diario di bordo» o «Diario personale» o «Diario» riescano a cogliere meglio il significato, traduzione non facile.
- **Per quanto cerchiamo, non potremo mantenere lo stabilizzatore dimensionale in eterno** «Per quanto ci proviamo», «Nonostante i nostri sforzi», «Per quanto gli stiamo dietro». 
- **Ah ah ah... credici** → Forse «Ah ah ah, ci sei cascato!» o «Ah ah ah, fessacchiotto!» o «Turlupinato!» o «Gabbato alla grande!» o «Infinocchiato!».
- **Tutto crolla, è una legge universale** Crolla non mi dispiace, la ma dimensione *collassa*, che mi pare più un termine fisico o fisicheggiante. «Tutto collassa prima o poi, è una legge universale».
- **Le cose si fanno difficili**, più semplicemente «Le cose si complicano» o magari se vogliamo mantenere difficile «Farla difficile». Mi era venuto in mente «Ufficio complicazione affari semplici», ma è troppo lungo. 
- ~~**Cancelli del cielo**: «Le porte del paradiso», come da traduzioni nei film/libri.~~ vedo che Terry stesso ha specificato il film del 1980.
- **Patron**: magari osare un «mecenati»? «Sostenitori»?

Ancora bravissimi tutti!

**Comment by TerryCavanagh** [comment]
Thanks @ffaf1! I'll pass this along to the translators!

**Comment by AlainDellepiane** [comment]
Hi ffaf1,

I'm Alain, editor for the project.
Thank you for your feedback. Most of the points you raise seem to loop back to four core choices you were not aware of, so I will summarize them here for brevity.

1) Gendering. We deliberately avoided gendering the player as much as possible. In other words, whenever we could write in a way that don't imply he's male, we would do that above other stylistic concerns.
2) Theatricality. We mimicked the somewhat outdated "naval" style of Star Trek. Similarly to how Picard would say "Make it so" and not "Do it", our characters use a somewhat higher register Italian, both through the use of polite forms and slightly outdated constructions.
3) Brevity. Despite the goal above, this is game is clearly more action-focused than narrative-oriented. Combined with the lower legibility of the large "retro" font being used, this led us to favor brevity as much as possible. Whenever two wordings were appropriate, we always went with the shortest.
4) Faithfulness. The game is replete with unexpected and oblique references, which were explained to us through detailed notes. Similarly to the original experience, we strived to recreate and maintain those reference as much as possible, despite knowing that many of them might be obscure and easily missed.

> Ora segui me Preferirei «ora seguimi» (visto che nella stanza dopo c’è «ora stammi vicino»).

Faithfulness. "This entire intermission section has a tone of a strict schoolteacher leading a small child." Segui me" is a stronger, more imperative form that would be used in that context.

> Coraggio, giovane, magari «Coraggio, giovanotto».

Same as above plus gendering.

>  Cosa? Non ho capito niente!, forse è meglio «Cosa? Non ci ho capito niente!», il ci — pronome? boh — è un po’ più spontaneo nel dialogo e indica meglio che l’interlocutore sta sbroccando.

Theatricality and brevity. Indeed, the character is losing control here, but we didn't want the register to slip too low. Also, the current form is slightly shorter and faster to parse.

> È una gioia riavere Victoria con noi Vedo che due personaggi usano questa locuzione, Victoria e il rosso. Che Victoria la usi può essere considerato un vezzo suo, ma Vermillion semplicemente può dire «È bellissimo che…», «È fantastico che…», «Che bello che…» o se proprio si vuole mantenere «Che gioia riavere Victoria con noi!».

Same as above. 

> In generale vedo «gioia» usato frequentemente come traducente di varie espressione (p.es. «You are ok!»). Non è sbagliato per carità però salta all’occhio perché appunto è frequente ed in bocca a quasi tutti i personaggi. Io limiterei ad uno e gli altri che se la cavino con «Benritrovato, Capitano!» «Sono felicissimo di esser qui» etc.

Same as above. Also consider that Captain Veridian is canonically gender-ambiguous and many of the solutions above wouldn't allow it.
    
> Registro personale: mhhhhhh non so se «Diario di bordo» o «Diario personale» o «Diario» riescano a cogliere meglio il significato, traduzione non facile.

Theatricality. 

> Per quanto cerchiamo, non potremo mantenere lo stabilizzatore dimensionale in eterno «Per quanto ci proviamo», «Nonostante i nostri sforzi», «Per quanto gli stiamo dietro».

Same as above.

> Ah ah ah... credici → Forse «Ah ah ah, ci sei cascato!» o «Ah ah ah, fessacchiotto!» o «Turlupinato!» o «Gabbato alla grande!» o «Infinocchiato!».

Brevity

> Tutto crolla, è una legge universale Crolla non mi dispiace, la ma dimensione collassa, che mi pare più un termine fisico o fisicheggiante. «Tutto collassa prima o poi, è una legge universale».

The original line is "...everything collapses, eventually. It's the way of the universe."
As such, it almost works as a double entendre, with a normal idiomatic nuance ("everything crumbles") and a scientific overtone layered on top ("everything goes through the physical process of collapsing").
Italian cannot do the same, since the idiomatic nuance and the scientific one require different terms. 
And since saying that "everything goes through the physical process of collapsing" is simply not true, we had to stick with the idiomatic form and lose the scientific overtone. It's a loss of nuance, but not a significant one in the larger picture of an action game

> Le cose si fanno difficili, più semplicemente «Le cose si complicano» o magari se vogliamo mantenere difficile «Farla difficile». Mi era venuto in mente «Ufficio complicazione affari semplici», ma è troppo lungo.

Faithfulness. The original text was "Doing Things The Hard Way", with a double meaning between an idiom ("doing things in an unnecessarily complicated manner") and the fact that you are taking the hardest path in the game.
Similarly our solution is a pun between a commonly used idiom that implies hard times are coming and the fact that things are literally becoming hard to do. 

> Patron: magari osare un «mecenati»? «Sostenitori»?

My understanding was that he received these donations through the Patreon website, which in turn forces our hand to keep this in English to maintain the relationship.

However, this would be factually wrong if the donations were collected directly, making "Sostenitori" the better solution. I will need to confirm this with Terry. 

> Ancora bravissimi tutti!

Thanks again for the kind words, help and support. Have a nice day.

**Comment by TerryCavanagh** [comment]
>My understanding was that he received these donations through the Patreon website, which in turn forces our hand to keep this in English to maintain the relationship.
>
>However, this would be factually wrong if the donations were collected directly, making "Sostenitori" the better solution. I will need to confirm this with Terry.

Oh, right, quick note on these - it was in 2009, and it was directly through paypal! https://distractionware.com/blog/category/vvvvvv/page/8/

**Comment by ffaf1** [comment]
Thanks @AlainDellepiane for the thorough explanation! Happy to see that at least some of the suggestions were accepted.

I will close this to keep the issue tracker tidy.
