### ISSUE TITLE
walking left into a gravity line and a spike is bugged

### ISSUE THREAD

**Issue by Klanker** [TerryCavanagh/VVVVVV#1193]
i doubt this bug affects anything in the main story levels, but i think it's still something to be fixed.

https://github.com/user-attachments/assets/2182130e-8590-4eb2-af15-0b3224beb7ad

when walking left into a gravity line and a spike right beside it, the gravity line sound effect plays only when viridian respawns (instead of it playing before the death sound). viridian also respawns a little higher (or lower, if the checkpoint is flipped) than they should.

interestingly enough, this effect is not present when walking into the same setup in the opposite direction.

i can only, like, vaguely speculate on why what happens happens, so i'll be leaving the discussion (and the coding) to y'all

**Comment by NyakoFox** [comment]
This is known, and also WONTFIX -- basically, when you touch a gravity line, it queues up the behavior to happen on the next frame. This timer gets paused while the player is dying, however, so that causes the behavior that you're experiencing -- touching the gravity line and dying waits until you respawn to activate the gravity line's behavior. There's no fix for this which wouldn't affect behavior in pre-existing levels and TASes.

**Comment by InfoTeddy** [comment]
This happens any time you die on the same frame as touching a gravity line. The only reason it doesn't happen in your setup while walking from left to right is because the hitbox of vertical gravity lines are to the left of their visual.
