### ISSUE TITLE
Historical context regarding loading mmmmmm.vvv and vvvvvvmusic.vvv?

### ISSUE THREAD

**Issue by GMMan** [TerryCavanagh/VVVVVV#276]
Just building for a weird low-powered platform here (AtGames Legends Flashback, if you're curious), and the slow loading time is leading me to comb through the code to see what's taking so long. I noticed in Music.cpp it's trying to load both mmmmmm.vvv and vvvvvvmusic.vvv. Although my version of data.zip only has vvvvvvmusic.vvv, I am curious that if both are present, why are both loaded? It seems only one set is used anyway, and going by the filenames they both contain the same files.

**Comment by InfoTeddy** [comment]
`mmmmmm.vvv` is the MMMMMM mod made by FamilyJules7x in collaboration with Souleye, the composer for the original soundtrack to the game, PPPPPP (also in `vvvvvvmusic.vvv`). It's not intended to be in `data.zip`, you're supposed to buy the MMMMMM album and get the music file as part of the download.

Both are loaded because if `mmmmmm.vvv` is present, the game will present an option in the "game options" menu to switch between MMMMMM and PPPPPP. Technically I guess the game could, instead of loading both at startup, just load the selected soundtrack in `unlock.vvv` upon startup and when the user switches the track, load the other one, but this requires more complicated code.

If you're trying to optimize for a low-powered platform, you could consider having `data.zip` already unzipped inside the VVVVVV folder (where the `saves/` and `levels/` folder are also located, on Linux this directory is `~/.local/share/VVVVVV`) because unzipping it in memory at startup (as the game does) takes much longer than reading it from a filesystem.

**Comment by GMMan** [comment]
Cool, thanks for the information!
