### ISSUE TITLE
Add XML forwards compatibility

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#373]
There's a semi-annoying issue with the game where if you downgrade to 2.2 and 2.2 writes its settings file, all your 2.3 settings are lost. This is because 2.2 writes only what 2.2 has and nothing else. It has no forwards compatibility. (The same issue also happens with 2.0, i.e. your 2.2 controller mappings and stuff will be lost if 2.0 writes its settings file.)

While there's basically no reason to downgrade to 2.2 after 2.3 is released (if you want credits warp or other glitches, just use glitchrunner mode), and while we can't really rectify this for 2.2, we could stand to introduce XML forwards compatibility in 2.3, which would be applied to all files, not just `unlock.vvv`. And this would mean preserving attributes that 2.3 doesn't have in XML elements that 2.3 does have, as well as preserving XML elements that 2.3 doesn't have, and so on.

Also, as @Dav999-v suggested in the comments below, we should also move all settings to a new `settings.vvv` XML file.

**Comment by Dav999-v** [comment]
Just thinking out loud, but it's a bit odd that settings can be found in the file called "unlock" anyway. Maybe it'd be a good idea to move all configuration to a separate XML file (like `settings.vvv`) where unknown elements are preserved from its inception, and leave `unlock.vvv` for game stuff like unlocks and records. If the new settings file doesn't exist, but `unlock.vvv` does, then it can copy settings from `unlock.vvv` to the new file.

Opening 2.2 won't suddenly destroy new 2.3 options anymore. After opening 2.3, settings common between 2.2 and 2.3 will be configured separately, but that's arguably much better than suddenly losing settings because you wanted to try out something in 2.2 or opened the wrong version accidentally.

**Comment by InfoTeddy** [comment]
I like that `settings.vvv` idea, too, and we should do it.

The main thing though is that in order to not duplicate the file spec a *third* time, we should somehow abstract each element and attribute into an abstract static constant data structure that we can easily read from to load and save data. And we'd still have to do that for moving the configuration settings into `settings.vvv`

Alternatively, I was thinking it was maybe possible to just open an XML document and update it instead of writing an entire new XML document to the file. It seems simple that you should be able to do that, right? I haven't looked into this further but that's maybe a starting point to adding XML forwards compatibility without having to duplicate file specs a third time, or having to abstract and refactor the file specs.

**Comment by Dav999-v** [comment]
You can update an existing XML document; I'm using it for the option to sync language files in my localization branch.

**Comment by InfoTeddy** [comment]
Yeah, hm, looking at it now, that seems simple enough. However, we'll still have to create an element if it doesn't exist in the file, as well as create an entire new file if the file doesn't exist at all, and I'm not sure how to best achieve those things without duplicating code.

**Comment by Dav999-v** [comment]
I guess at least when creating a new file because it doesn't yet exist, we don't have to initialize a document with all settings in it, we can simply create a document with no settings. Then the "create an element if it doesn't exist in the file" part can populate it.

**Comment by flibitijibibo** [comment]
So far everything makes sense, and I'm willing to make a freeze exception for settings.vvv; separating the settings and unlock data will allow us to enable Steam Auto-Cloud without unintentionally dragging settings from another machine. That said, because it's a feature it's still a much lower priority than the rest of the issues marked for 2.3.

**Comment by InfoTeddy** [comment]
Hm, we would still have to keep a copy of the settings in `unlock.vvv`, like I did with `levelstats.vvv`, right? Otherwise if someone launches 2.2 they'll find that some 2.2 settings don't work.

**Comment by flibitijibibo** [comment]
#487 is merged, what's left before this one's ready?

**Comment by InfoTeddy** [comment]
Just moving the settings-specific parts of `unlock.vvv` to `settings.vvv`. Should be simple enough to do...
