### ISSUE TITLE
Game softlocks upon entering teleporter immediately after rescuing a crewmate

### ISSUE THREAD

**Issue by vmrosetta** [TerryCavanagh/VVVVVV#391]
If you enter the teleporter in the ship immediately after rescuing a crewmate, and no cutscene plays, the game softlocks. The "Game Saved" dialog appears as it normally does after the teleport finishes, but the sequence stops after entering the teleporter, making it impossible to use any inputs/menus.

**Comment by InfoTeddy** [comment]
I can't seem to repro this.

After I rescue Victoria and go through the Level Complete cutscene, teleport out of the teleporter at the ship, and then immediately afterwards press Enter, then Left/Right to select a different teleporter, then press Enter again, and I teleport out of the teleporter just fine.

I have a feeling that maybe Undefined Behavior is at play here...

**Comment by flibitijibibo** [comment]
May be a situation similar to #392? Valgrind may be able to spot the UBO if that's still happening.

**Comment by InfoTeddy** [comment]
> May be a situation similar to #392?

Well, I don't think so.

@vmrosetta forgot to mention this, but this happens regardless of having Glitchrunner Mode on or off, and this softlock also existed in 2.2.

**Comment by InfoTeddy** [comment]
> Valgrind may be able to spot the UBO if that's still happening.

Just tried to do the softlock again under Valgrind, and it doesn't say anything. What does UBO stand for?

**Comment by InfoTeddy** [comment]
Alright, so apparently @vmrosetta left out critical information in her initial report, which she only told me just now. You have to move left first, and then after that activate the teleporter and teleport somewhere. Then a "Game Saved" text box comes up, but you're still in the Ship room, and you're softlocked. And *now* I can reproduce the softlock consistently 100% of the time.

So it looks like there's a certain threshold you have to reach when you move leftwards in order for the softlock to happen. You don't have to move left very far, but if you move only a few pixels left it doesn't seem like the softlock happens, either. At the very least, though, there seems to be two regions of the teleporter prompt zone, and the left region softlocks you if you use the teleport and teleport somewhere after rescuing a crewmate, and the right region doesn't softlock you but is much smaller than the other one.

Also I made extra sure that this softlock happens *only* after rescuing a crewmate and teleporting out of the teleporter. When you do that, you can move as far rightwards as you want without leaving the Ship teleporter room, and then come back to the left region of the teleporter, use it, and then softlock. But if you exit the Ship teleporter room and re-enter it, then the softlock won't happen.

My intuition suggests that this softlock is probably caused by the crewmate entity that spawns and walks off-screen whenever you teleport to the Ship after rescuing them. After all, it doesn't seem like they get destroyed when they walk off-screen (unlike the supercrewmate in Intermission 1), and that's basically the only difference I can think of between a regular teleport to the Ship and a teleport to the Ship after rescuing a crewmate. I will be debugging with GDB now.

**Comment by InfoTeddy** [comment]
Yeah, so it seems like for whatever reason, the teleport animation gets interrupted, the gamestate is 0 and `game.hascontrol` is false.

I've had this idea earlier, but I guess now's a good of a time as any to write it down: the game should set `game.hascontrol` to true if there's no gamestate running right now (`game.state` is 0) and if there's no script running right now (`script.running` is false). There are many different ways to interrupt gamestates and scripts and be softlocked by being stuck in a state where `game.hascontrol` is set to false, and it's always good to have catch-all softlock protection.

Also, the game should let you press Esc or Enter even if `game.hascontrol` is set to false. That way even if the above softlock protection somehow fails, at least you can be rest assured you can save your game, quit to the menu, and try again.

I'm gonna keep debugging for now.

**Comment by InfoTeddy** [comment]
(If you don't want to read this long post, just skip to the very bottom of it where it details the chain of events leading to the softlock.)

So, the teleporting animation is controlled by this terrible thing called Terry's State Machine (which I'll just refer to as gamestates from now on). Different teleporters have different gamestates, but they're all just copy-pasted after each other anyway, so it doesn't really matter.

Anyways, whenever you use a teleporter, there's a first part where the screen shakes and flashes and Viridian teleports out (that's just them turning invisible), and there's a second part where the game loads the next room (this is called a gotoroom) and Viridian appears (that's just them turning visible again) and is flung out of the teleporter. I'll only be focusing on the first part, since that's the only relevant part.

The gamestate sequence for the first part goes like 4000 -> 4001 -> 4002 -> 4003. Whenever you use any teleporter, this is the gamestate sequence that's supposed to take place.

However, whenever this softlock happens, the gamestate sequence is a little different. It first goes like 4000 -> 4001 -> 4002 like normal. And then it gets to gamestate 4003.

However, for whatever reason, it gets set to gamestate 2000 *on the same frame*. Thus, gamestate 4003 has no chance to execute, and this is crucial, because what gamestate 4003 does is set the flag that says to gotoroom to the room to be teleported to (`game.teleport_to_new_area`), and if that flag isn't set, then Viridian is stuck in a state where `game.hascontrol` is false and the game is softlocked.

So, the sequence when this softlock happens is essentially 4000 -> 4001 -> 4002 -> 2000.

What's gamestate 2000, you may ask? Well, it's the gamestate that gets triggered whenever you touch a teleporter. It automatically saves your game in the teleporter save, and creates the "Game Saved" text box.

So... for some reason, instead of properly teleporting Viridian, the game decides to randomly save your game instead, and then you get softlocked.

Now, why does gamestate 2000 get set? Well, it gets set because of `entityclass::updateentities()`. This is simply a function that updates entities' states, usually relating to what happens when Viridian touches them.

Anyways, so what happens in `entityclass::updateentities()`? Well, entity type 100 is evaluated, and that's simply the type number of the teleporter, in this case being the teleporter in the Ship room. There's an if-statement that checks if its `state` is 1. An entity's `state` is just some number that signifies what the entity should do, and usually a `state` of 0 means "do nothing".

Within that if-statement, there's another if-statement that checks if its `tile` is 1. An entity's `tile` is basically its base sprite offset, which is the starting point the game uses before applying some calculations to produce the entity's `drawframe`, which is the real sprite number that actually gets drawn.

And then, inside *that* if-statement, `game.state` gets set to 2000. This routine is intended to be ran whenever Viridian touches the teleporter and it hasn't been touched before.

So, to summarize, GDB says that **the gamestate got set because Viridian touched the teleporter when it was inactive**. Huh? But the teleporter is already active, what are you talking about?!

Alright, let's work backwards. How does the game know that Viridian touched the teleporter?

Well, this is done with the `onentity` attribute of entities. Whenever Viridian touches an entity, the entity's `state` is set to the value of `onentity`. So you should read an `onentity` attribute as "if Viridian touches me, go to this state".

Normally, after you've touched the teleporter, its `state` gets set to 0 and its `onentity` is 0 as well.

However, for whatever reason, the `onentity` of the Ship teleporter is 1 after rescuing a crewmate. This explains the fact that you have to move left a little bit in order for the softlock to happen. You actually have to be touching the teleporter itself to softlock when you use it, because its `state` has to be 1 in order to trigger the softlock. That explains the weird left-right regions thing I observed earlier. Likewise, if you move all the way left and are not touching the teleporter anymore (there's no accessible space left of the teleporter where the teleport prompt zone ends), the softlock won't happen.

By the way, the teleporter hitbox is 96 pixels by 96 pixels, which is just a square that perfectly bounds the round teleporter. It doesn't have a circular hitbox, so in the corners you could appear to not be touching the teleporter, even though you are.

But, again, let's go back to what I said above about what the teleporter does when its `state` is 1. When its `state` is 1, it should just do gamestate 2000 and then go back to having a `state` and `onentity` of 0, right?

Well, wrong. There's an if-statement inside the routine that gets executed if the teleporter's `state` is 1. The if-statement checks if the teleporter's `tile` is 1 before proceeding with doing gamestate 2000 and setting the `onentity` to 0.

Right now, the teleporter's `tile` is 2, so nothing happens when its `state` 1 gets ran, meaning its `onentity` is always 1.

Alright, let's work backwards some more. So, there's a main game script that gets run after you do the Level Complete sequence. It's named `regularreturn`, and all it does is gotoroom to the Ship teleporter room, create the last rescued crewmate, and do gamestate 4010.

By the way, it's also used whenever you return from an intermission, so you can do this softlock after teleporting back to the Ship from Intermission 1 or Intermission 2.

Alright, but what's so bad about the `regularreturn` script? Is it the fact that it does gamestate 4010? Well, all that gamestate 4010 does is just the sequence to fling Viridian out of the teleporter, and that's just the sequence used by the Ship teleporter. The gamestate sequence goes like 4010 -> 4011 -> 4012, and then after that is just a bunch of gamestates for positioning Viridian, all the way up to and including gamestate 4019.

Also, gamestate 4010 is used every time you teleport to the Ship. But the softlock doesn't happen every time you teleport to the Ship, it only happens when you teleport to the Ship after rescuing a crewmate or returning from an intermission.

So there can't be anything wrong with that gamestate. At the most, that gamestate sequence will just be setting up something for some other part of the code to make an error.

And in fact, it seems like the problem with the `regularreturn` script is what it *doesn't* do. Let's first start by seeing how a normal teleport works:

 1. The game does a gotoroom to the destination room. (`scriptclass::teleport()`)
 2. The teleporter's `state` is set to 2. (`scriptclass::teleport()`)
 3. The teleporter's `state` 2 runs, and then gets set to 0. Its `onentity` gets set to 0 as well. (`entityclass::updateentities()`)
 4. Viridian gets moved to the position of the teleporter, and thus touches the teleporter.

Now, let's see what the `regularreturn` script does instead:

 1. The game does a gotoroom to the destination room, in this case the Ship teleporter room. (`regularreturn` script)
 2. Viridian gets moved to the position of the teleporter, and thus touches the teleporter.
 3. Because Viridian touched the teleporter, the teleporter's `state` gets set to 1.
 4. The teleporter's `state` 1 runs, and then gets set to 0. However, its `onentity` is still 1. Meaning if Viridian touches it, it will keep running its `state` 1.

And so, since the teleporter's `onentity` is 1, it will perpetually run its `state` 1 whenever Viridian is in contact with its hitbox. However, it doesn't do gamestate 2000 just yet, because its `tile` is 2. Its `tile` has to be 1 in order for it to actually run its `state` 1. So when is its `tile` get set to 1?

Well, that happens when you press Enter on the teleporter. Pressing Enter will set its `tile` to 6 initially. And then the gamestate sequence of 4000 -> 4001 -> 4002 -> 4003 gets ran. It is specifically in gamestate 4002 that its `tile` gets set to 1.

And with all of the above laid out, let's summarize what the sequence of events are.

Thus:

 1. The softlock happens because `game.hascontrol` is false (and there's no script or gamestate running to save us from it)...
 2. ...because gamestate 2000 got ran in the middle of the teleport animation...
 3. ...because the teleporter's `state` 1 got ran...
 4. ...because its `state` is 1.
 5. (3) only happened because its `tile` is 1 (otherwise its `state` 1 would just do nothing)...
 6. ...because gamestate 4002 set its `tile` to 1.
 7. (4) happened because Viridian was touching the teleporter...
 8. ...and the teleporter's `onentity` is 1...
 9. ...because its `state` 1 never reset its `onentity` to be 0 (for reason (5)).
10. (6) happened because of the gamestate sequence that runs whenever you activate a teleporter (4000 -> 4001 -> 4002 -> 4003).
11. (7) happened because Viridian was moved to the position of the teleporter...
12. ...because the `regularreturn` script was being run...
13. ...and if Viridian had teleported in any other way, the teleporter's `state` would get set to 2, then would run and set its `onentity` to 0.
14. And (12) happened because Viridian teleported in after rescuing a crewmate or returning from an intermission.
