### ISSUE TITLE
Remove word “open” from repo description

### ISSUE THREAD

**Issue by Wuzzy2** [TerryCavanagh/VVVVVV#44]
Current repo descriptoin:

> The source code to VVVVVV, now open and public! 

As this game is not an open source game, I recommend to remove the word “open” to avoid misleading users.

This game is not open source software as the license is too restrictive to meet the Open Source Definition (namely, commercial). The correct term is “source-available software”.

https://en.wikipedia.org/wiki/Source-available_software
https://opensource.org/osd

**Comment by flibitijibibo** [comment]
Should be easy enough to fix. @TerryCavanagh?

**Comment by RoestVrijStaal** [comment]
The code IS open. It's not however free as in the FSF's ~ugly~ definition of "free". 

Also, the OSI is a ["company with an agenda"](https://opensource.org/about) , and not a standards agency like the [ISO](https://en.wikipedia.org/wiki/International_Organization_for_Standardization). 
Thus the authority of the OSI is like "Any fool can make a rule, and any fool will mind it."¹

Anyhow, stop demanding license changes. Swallow the decision of Terry or create your own viral licensed VVVVV-clone. 

¹ from Henry David Thoreau

**Comment by kitlith** [comment]
@RoestVrijStaal the author(s) have already shown they are willing to change the terminology used, and in fact already has on the announcement post (and elsewhere?), so this issue is basically just "you missed a spot", waiting on the person who owns the repository to change the description.

I would find your comment much more understandable they said "no, we're not changing the wording, because xyz" and then this issue popped up. If you want to argue with the people requesting a different license, then maybe you should head over to #7?

**Comment by TerryCavanagh** [comment]
Sure, I'll change the description.
