### ISSUE TITLE
SDL2 target doesn't imply SDL2_mixer target

### ISSUE THREAD

**Issue by leo60228** [TerryCavanagh/VVVVVV#542]
On my system, the `SDL2::SDL2` target is available, however `SDL2_mixer` is not. SDL2_mixer is also installed at a different path from SDL2. Together, this leads to compilation failing due to `#include <SDL_mixer.h>` not being found.

**Comment by flibitijibibo** [comment]
The expected behavior is for the satellite libraries to be installed within the same directories - this is an expectation set by SDL itself, mainly through `sdl2-config` but also SDL's CMake install target. Any issues with this need to be directed toward the build system in SDL and SDL_mixer, not any application or library using it.

**Comment by leo60228** [comment]
So, on Linux distributions where packages are installed in their own
directories, would you suggest that the SDL2 package have a build flag to
enable SDL_mixer instead of having separate SDL2 and SDL2_mixer packages?

**Comment by flibitijibibo** [comment]
`sdl2-config` and the SDL CMake variables would need to be modified by the distribution to include the directories of the extra libraries if they want to replicate expected behavior. The sublibraries don't control either of those, so the distributor will have to get creative with their SDL configuration (or they need to fix the directories of the packages as that's not how those libraries are supposed to be installed to begin with).

**Comment by leo60228** [comment]
> `sdl2-config` and the SDL CMake variables would need to be modified by the distribution to include the directories of the extra libraries if they want to replicate expected behavior.

My distro (NixOS) already does this for SDL2_INCLUDE_DIRS, I'm opening a bug for that not applying to the SDL2::SDL2 target.
