### ISSUE TITLE
Segfault on startup if unlock.vvv or settings.vvv is missing

### ISSUE THREAD

**Issue by leo60228** [TerryCavanagh/VVVVVV#556]
https://github.com/TerryCavanagh/VVVVVV/commit/e73c14d1f373905f3d16c77947b6fba7474d678e removes the "unnecessary" Screen options from Game. However, they're there for a reason: Screen is created after settings are loaded, and settings are saved automatically when loading them without an existing save. This leads to a segfault due to dereferencing the null `screenbuffer` pointer.

**Comment by InfoTeddy** [comment]
> However, they're there for a reason: [reason]

I don't think that's quite the full story.

These duplicate variables already existed in 2.2, where `Screen` was created (initialized) *before* `game.loadstats()` got called. With the merging of #220 and the addition of the VSync option, we ran into a bug with SDL2 where toggling the VSync flag wouldn't apply until the renderer got destroyed and re-created. So after working around that, we also made it so `Screen` got created *after* `game.loadstats()` got called, so we wouldn't unnecessarily destroy the renderer and re-create it again. And this was necessary to fix, because the reset renderer workaround doesn't work on Haiku; you need to close the game and open it again, but if the game does the workaround on startup, then there's no way for the VSync option to properly apply on startup.

All of that is to say, it's completely anachronistic to say those duplicate variables were there because of 2.3 startup order, when they already existed previously in 2.2. And I still stand by my thinking that those duplicate variables shouldn't exist.
