### ISSUE TITLE
Deceleration takes an extra frame over 2.2

### ISSUE THREAD

**Issue by leo60228** [TerryCavanagh/VVVVVV#577]
See discussion in #576. This does not appear to be related to float/integer casts, as the disassembly for 2.2 matches `SDL_fabsf`.

@InfoTeddy

**Comment by InfoTeddy** [comment]
Yep! After releasing a directional key held for 5 frames, Viridian decelerates for 4 frames in 2.0 and 2.2, and 5 frames in 2.3. I don't know why this is the case either, but I do suspect it might be a result of replacing an `std::abs()` with a wrong equivalent somewhere (not necessarily related to #576, it would be a different `std::abs()` replacement somewhere else).

**Comment by leo60228** [comment]
I can't reproduce this, but it might be an issue with my testing methodology. I'm logging `vx` when `applyfriction` is called on entity 0, and I see 4 frames of deceleration on both 2.2 and master. Can you reproduce this with a freshly rebuilt 2.2? It might be UB.

**Comment by leo60228** [comment]
I thought this might be a frame ordering issue, but I get the same results doing it at the end of each frame in main.cpp.

**Comment by InfoTeddy** [comment]
I found the issue with my methodology - my frame counting was wrong, because I had over-30 mode on, and was counting frames based on Viridian's interpolated visuals, instead of their actual position.

Using libTAS again but this time with over-30 mode off, it clearly shows 4 frames of deceleration. This can be closed.
