### ISSUE TITLE
SDL in Ubuntu stable releases is too old

### ISSUE THREAD

**Issue by Dav999-v** [TerryCavanagh/VVVVVV#618]
These commits added the use of `SDL_zeroa()`:
70b9ffe6a58b71122aa60280bae4194326d026a0
a113662050d29a01819a2f606c9bb1d55d941abb
bd97378862c6b01d1de59f59a98a8a53a74fb696

The problem is that `SDL_zeroa()` was [added in SDL 2.0.12](https://github.com/libsdl-org/SDL/blob/983bbf9ef3e572a073a6f5877faf1c0b4803527c/WhatsNew.txt), and the earliest version of Ubuntu that can easily install SDL 2.0.12 via `apt` is the very latest, Ubuntu 20.10 (see [20.04](https://packages.ubuntu.com/focal/libsdl2-dev) and [20.10](https://packages.ubuntu.com/groovy/libsdl2-dev)), and 20.10 is not an LTS version.

So now anyone on most versions of Ubuntu or related distros (or anywhere else an earlier SDL is used than March 2020) will get a compilation error and will have to be told their SDL is too old. This makes "just" compiling VVVVVV more difficult on those systems.

**Comment by flibitijibibo** [comment]
Has a report been filed to Canonical to update to 2.0.14? If we can fix it on that end instead that'd be preferred, as we'll eventually be moving to 2.0.16 for some stdlib functionality anyhow.

**Comment by Dav999-v** [comment]
I don't know about any method to file a report to Canonical or where to find out whether anyone has done it, but in my experience it's pretty standard that they keep packages on whichever version was latest before the original date of that Ubuntu release (unless required for security), and only newer releases get newer versions.

**Comment by leo60228** [comment]
Packages will only be backported into Ubuntu itself due to major bugs, however users can opt-in to updating specific packages through the Ubuntu Backports Project.

`requestbackport` in the `ubuntu-dev-tools` package is an interactive tool for submitting backport requests with the required metadata.

**Comment by dsalt** [comment]
I have SDL 2.0.14 installed here, and I doubt that I'll be updating past that before Debian's next release (though I'm actually using Devuan) – and if I do it'll most likely be via backports.

The only times that I've seen newer versions being pulled into an existing distribution release are to pull in some security bug fixes but the fixes are too big or too invasive for the maintainers to handle as patches.

(Incidentally, Debian's previous release, buster, has SDL 2.0.9.)

Regarding `SDL_zeroa`, if there's nothing else being used which isn't in 2.0.12, you could get away with including (after SDL includes) a compatibility header file containing
```c
#ifndef SDL_zeroa
# define SDL_zeroa(x) SDL_memset((x), 0, sizeof((x)))
#endif
```
(on the assumption that 2.0.12 has SDL_memset, which seems likely).

**Comment by leo60228** [comment]
For what it's worth, 2.4 will likely require 2.0.18/2.0.20 due to action sets, and it won't be easy to backport.

**Comment by InfoTeddy** [comment]
I'd also like to mention that with the new VSync API merged into SDL 2.0.18, 2.4 has already dumped the VSync renderer workaround in favor of that API. This doesn't cause builds to fail, but it does mean builds compiled on an SDL older than 2.0.17 cannot toggle VSync in-game.

I also upgraded the minimum version to 2.0.16 due to using some new stdlib functions that got merged in that version as well.

**Comment by InfoTeddy** [comment]
Homebrew does sound way easier than having to manually download all build dependencies and compile SDL yourself... @Dav999-v, does this solution work for you?

**Comment by Dav999-v** [comment]
Personally I'd like to avoid bloating my system unnecessarily, so I'd think really well about installing something like Homebrew over just compiling SDL myself instead, but for people who don't care as much about that, it's certainly an option. A PPA for recent SDL versions would also be nice (apparently there is one with a lot of packages including SDL 2.0.16 [here](https://launchpad.net/%7Esavoury1/+archive/ubuntu/multimedia/+index?batch=75&memo=375&start=375), but it seems to have only `libsdl2` and not `libsdl2-dev`, so if I'm not mistaken that would only help if VVVVVV didn't come with a `.so` for SDL, but it does).

**Comment by stephendcofer** [comment]
Also even on latest Ubuntu (21.10) SDL_isxdigit isn't available since 21.10 uses SDL2 2.0.14 and "is characteristic" stdlib functions in SDL was added in 2.0.16, breaking compilation even on latest Ubuntu.  Not going to risk breaking anything by manually upgrading Ubuntu; I just added the SDL_isxdigit function to desktop_version/src/UtilityClass.cpp as a hack to get it to build.

**Comment by InfoTeddy** [comment]
> Bad practice to throw in brand new functions from versions of libraries that aren't even on most distros yet.

Then how do you suggest we toggle VSync? As I [noted above](https://github.com/TerryCavanagh/VVVVVV/issues/618#issuecomment-938380209), SDL 2.0.18 has a new dedicated VSync toggle function, to fix a problem where toggling VSync required a hacky workaround by tearing down everything and rebuilding (which didn't work on some systems). It's hidden behind a `#if` until 2.0.18 releases.

Also, you said "libraries", plural, but we only have external build dependencies for SDL2 and SDL2_mixer (and SDL2_mixer is going to be axed in favor of statically linking FAudio) - all other dependencies have had their source copied in and are statically linked by default - so arguably, we only have *one* library with "brand new functions [...] that aren't even on most distros yet".

**Comment by flibitijibibo** [comment]
I also question the "most distros" part, because as far as I know the following all have 2.0.16:

- Arch
- Gentoo
- Fedora
- OpenBSD
- Testing stage in FreeBSD
- FreeDesktop Flatpak SDK
- Steam Runtime (Scout and Soldier)

As far as I know it's just Debian-based and RHEL-based, and only at the system repo level (developer environments like the last two above are fine). Even as a CentOS 7 user myself it's not _that_ big of a deal to self-build libraries that I expect to use regularly (and for releases we provide SDL ourselves anyway).

(And frankly I don't care that Ubuntu falls into the Debian umbrella - user support for Ubuntu and friends is 99% linking people to PPAs like kisak-mesa, so having this be the experience for developer support as well is no surprise to me.)

**Comment by InfoTeddy** [comment]
> I also question the "most distros" part, because as far as I know the following all have 2.0.16:

Almost all of these can be easily verified using [Repology](https://repology.org/project/sdl2/versions).

* Arch: https://archlinux.org/packages/extra/x86_64/sdl2/
* Gentoo: https://packages.gentoo.org/packages/media-libs/libsdl2, and I can personally confirm this because I use Gentoo
  ```
   ~  equery y libsdl2
  Keywords for media-libs/libsdl2:
               |                             |   u   |
               | a   a     p s   a   r       |   n   |
               | m   r h   p p   l i i m m s | e u s | r
               | d a m p p c a x p a s 6 i 3 | a s l | e
               | 6 r 6 p p 6 r 8 h 6 c 8 p 9 | p e o | p
               | 4 m 4 a c 4 c 6 a 4 v k s 0 | i d t | o
  -------------+-----------------------------+-------+-------
  [I]2.0.16-r1 | + + + ~ + + + + ~ ~ ~ o o o | 8 o 0 | gentoo
  ```
* Fedora: https://src.fedoraproject.org/rpms/SDL2/tree/f34
* openSUSE: https://software.opensuse.org/package/SDL2
* Alpine: https://pkgs.alpinelinux.org/packages?name=sdl2-dev
* Slackware: 2.0.16 but no link on Repology
* Solus: https://dev.getsol.us/source/sdl2/
* Void: https://github.com/void-linux/void-packages/tree/master/srcpkgs/SDL2
* OpenBSD: https://openports.se/devel/sdl2
* FreeBSD: Testing stage isn't listed on Repology, but I did find [this bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252371)

**Comment by leo60228** [comment]
NixOS has an open PR for updating SDL to 2.0.16, but there were issues with
the libdecor dependency. It looks like those should be solved soon, though.

**Comment by Dav999-v** [comment]
As for me (since I opened this issue), I went with just compiling SDL myself. All I did was remove apt's versions of SDL, SDL_mixer and SDL_image, then `apt install` all the packages that it says are no longer necessary (to mark them as manually installed) and then just `./configure`, `make` and `sudo make install` SDL and SDL_mixer. I've had no problems so far, but if you ever want to go back to apt's version, you can always `sudo make uninstall`.

The most straightforward resolution I originally started this issue for (just sticking to an older SDL version in VVVVVV for compatibility) seems to be a WONTFIX, at least for now - the VSync thing and action sets kinda make it unattractive to stick to an older version here, but of course it's always possible to slow down our SDL version requirements from this point onwards and let the problem go away again by itself in a year or so (or at least not let stuff like c94d04a932b0bb90d3ede1d3a90c1a42b05404bc determine the minimum version when it's arguably not worth it).

**Comment by InfoTeddy** [comment]
> (apparently there is one with a lot of packages including SDL 2.0.16 [here](https://launchpad.net/%7Esavoury1/+archive/ubuntu/multimedia/+index?batch=75&memo=375&start=375), but it seems to have only `libsdl2` and not `libsdl2-dev`, so if I'm not mistaken that would only help if VVVVVV didn't come with a `.so` for SDL, but it does)

Revisiting this... As far as I know, the only difference between `libsdl2` and `libsdl2-dev` is that `libsdl2-dev` provides the header files in `/usr/include`. As you imply yourself, `libsdl2` only provides the `.so`. (Also, `libsdl2-dev` provides a `.a` file for static linking, but we don't statically link SDL.)

So if this is all that your problem is, then can't you just copy the SDL2 header files to `/usr/include`? (And if you don't want unmanaged header files, then, just put them somewhere nice and use the `-DSDL2_INCLUDE_DIRS` CMake option when `cmake`ing VVVVVV.)

**Comment by Dav999-v** [comment]
Hm, I guess that's another option that people might feel more comfortable with then.

Isn't it an option likewise to manually compile SDL but not install it system-wide, and then pass `cmake` some more arguments to point to your compiled version? `-DSDL2_LIBRARIES`, from a quick look? If that works, it's probably gonna be the most reassuring option out there for anyone.

**Comment by InfoTeddy** [comment]
Yes, `-DSDL2_LIBRARIES` should work too, then.

If those options work for everyone, then I think we should close this issue as fixed. Namely, you can either compile SDL or grab the `.so` from somewhere (such as the Steam release, or the [savoury1](https://launchpad.net/%7Esavoury1/+archive/ubuntu/multimedia/+index?batch=75&memo=375&start=375) PPA). Then install SDL system-wide, or use the CMake variables `-DSDL2_INCLUDE_DIRS` (after placing the downloaded header files somewhere okay) and `-DSDL2_LIBRARIES`. Or use Homebrew.

Unless someone really *really* wants a `libsdl2-dev` PPA, I don't think there's much else we can do, short of twisting the arms of Canonical.

**Comment by InfoTeddy** [comment]
Actually, looking at the savoury1 PPA some more, the [package details for `libsdl2`](https://launchpad.net/~savoury1/+archive/ubuntu/multimedia/+packages?field.name_filter=libsdl2&field.status_filter=published&field.series_filter=) say that it includes `libsdl2-dev` as well:

![libsdl2-dev](https://user-images.githubusercontent.com/59748578/140631880-cd0a25b9-b7c7-4bbf-909d-293d76997ad5.png)

Can someone who has an Ubuntu box check if installing this PPA will let them install `libsdl2-dev` 2.0.16?

**Comment by Fussmatte** [comment]
> Can someone who has an Ubuntu box check if installing this PPA will let them install `libsdl2-dev` 2.0.16?

Not sure if it's too late to confirm, but installing that PPA did let me upgrade my SDL2 packages so that the game could successfully compile.

**Comment by InfoTeddy** [comment]
It's not too late, but I'll take that as confirmation that the savoury1 PPA *does* provide `libsdl2-dev`, and not merely `libsdl2` (without the headers).

**Comment by leo60228** [comment]
> Actually, looking at the savoury1 PPA some more, the package details for libsdl2 say that it includes libsdl2-dev as well:

This is because compiling SDL2 produces both packages. It'd be kind of silly to build it twice, once just for the headers.

**Comment by InfoTeddy** [comment]
Okay, so, at this point, unless Canonical is willing to change (which, speaking from personal experience, institutions are big and dumb and not likely to do that), and you don't want to upgrade to an unstable version, or don't want to switch distros, there are many workarounds to get the latest version of SDL on Ubuntu (in order of easiest to hardest):

1. Install the [savoury1 multimedia PPA](https://launchpad.net/~savoury1/+archive/ubuntu/multimedia/), which makes the latest `libsdl2-dev` available.
    ```
    sudo add-apt-repository ppa:savoury1/multimedia
    sudo apt-get update
    ```
2. Install [Homebrew](https://brew.sh) for Linux. Then it's just a simple `brew install sdl2`.
3. Manually download the latest SDL and compile it from source.
   * If you don't want to install it system-wide (which would mean having an unmanaged package), then when you `cmake` the game, use the `-DSDL2_INCLUDE_DIRS` and `-DSDL2_LIBRARIES` variables to point to your copy.

With the VSync stuff and potentially having action sets, we are not going to be slowing down SDL upgrades anytime soon. (And there's no telling that we may need something new from SDL in the future, too.) All I can say is to just be glad that we're not using, like, C++9999 or whatever, or Rust nightlies.

**Comment by leo60228** [comment]
> Rust nightlies

I mean, Rust nightlies are easy for end-users, and every distro can handle
them because of Firefox.
