### ISSUE TITLE
[Docs] License is not open source

### ISSUE THREAD

**Issue by purpleidea** [TerryCavanagh/VVVVVV#7]
It's cool that you released the code! Unfortunately it's not actually an open source license!

I would recommend you use something like the GPLv3+ like John Carmack did when he release Quake source.

Happy to answer any licensing questions you have! Good luck!

**Comment by flibitijibibo** [comment]
We definitely misused the "open source" terminology; I think we've scrubbed all the references but if we missed any, let us know. The license will probably stay as-is, however.

**Comment by purpleidea** [comment]
> The license will probably stay as-is, however.

That's too bad! I don't see how this license benefits you or anyone, so I'd advise rethinking the choice, or at least explaining it here. A proper license gives your code a chance to grow and live on in Debian and other cool places. Cheers!

**Comment by Kissaki** [comment]
It’s still an incredible educational, exploration and archiving resource even without a FOSS or OSI license. So I have to strongly disagree with it not benefiting anyone.

While there is an OSI definition of open source I don’t think it’s prevalent enough that people using the term open source for projects where the source code is available in the open have to change their wording. That’s established just as much. Not in all communities, but still.

**Comment by Calinou** [comment]
I'm inclined to agree with OP as well. [Non-commercial clauses](https://freedomdefined.org/Licenses/NC) don't really  provide anything that a copyleft license would provide today.

**Comment by Moth-Tolias** [comment]
considering that the art - and any/all other assets not in this repo - are already not licenced for public use, having the noncommercial clause [which i believe is the only thing preventing this licence from being "truly" open source?] seems rather unnecessary.

**Comment by Cpt-Derp** [comment]
If you're gonna release the source code, following the example of John Carmack (id Tech 1-4 and Quake/Quakeworld engines) wouldn't do harm, and would foster a healthy modding community.

**Comment by benwiley4000** [comment]
1. Who cares what OSI decided or authorized, they don't get to control the free/OSS software community.
2. I don't see how there's any harm in the license specifying that you can't sell this game as your own.
3. The modding community has full license to work with the source code and release alterations (free of charge albeit). If they want to release modifications that include original assets and they want to work out an agreement with the creators of the game, the license permits that.

The one thing I would say is that it would be nice to modders to leave a way for them to earn income from their work if they put significant effort into a mod/extension that broadens the lasting appeal of VVVVVV as a product that people spend money on. Historically this hasn't been the case for game mods but there's an increasing awareness that modders increase the lasting value of games and help bring in profits for the companies whose games they mod.

But I don't understand the call for a "real" open source license authorized by OSI. OSI is an organization created to make open source code more appealing for adoption by corporations. It's largely irrelevant to an indie dev releasing the source code to their commercial game.

**Comment by dos1** [comment]
> It's largely irrelevant to an indie dev releasing the source code to their commercial game.

Except it is. OSI and FSF definitions of "open source" and "free software" are commonly used almost everywhere (and if they're not, it's usually just ignorance or lack of knowledge than anything else) and are basis of rules around many projects with very tactile and practical implications - for instance, if a license doesn't match OSI definition, then it almost certainly also doesn't match DFSG, which means it cannot be distributed as part of Debian. The same thing applies to plenty of other distributions as well.

purpleidea pointed out a valid and specific issue, flibitijibibo reacted sensibly and professionally, kudos for that. All this "OSI definition doesn't matter" talk that happened afterwards should probably go to some other place, like personal blogs, not here.

**Comment by liamdawson** [comment]
I think the primary benefit to OSI approved licensed is that they're known enough that you don't always need a lawyer. That being said, I understand the primary reason for opening this repo is to provide inspiration and examples for indie devs. General licensing politics aside, the license for this project seems to achieve those stated goals.

**Comment by piedoom** [comment]
The source is open. That is open source. The license is not free - open source is not always "free". That's fine. Thank you for opening this repo for us to see in the first place.

**Comment by purpleidea** [comment]
On Fri, Jan 10, 2020 at 6:40 PM alexander <notifications@github.com> wrote:
>
> The source is open. That is open source. The license is not free - open source is not always "free". That's fine. Thank you for opening this repo for us to see in the first place.

That's not how that works. There is a lot of source which is viewable
but proprietary. Just look inside any proprietary device that has a
non-compiled language as part of its coding.

**Comment by natis1** [comment]
This license is very similar to CC BY-NC-SA. Yeah that might not be open or free from your perspective but my opinion is that this is absolutely fine and it’s frankly a great thing that we have the code at all.

It’s the developers’ decision if the code should be used commercially and I see no reason why they should allow that. If you are a corporation interested in selling a game using this code I’m sure you could work out a business deal.

**Comment by coderbot16** [comment]
There's a critical distinction between *open* source, which grants an array of freedoms, and *shared* source, which restricts important freedoms. The current license lies somewhere in between, but NC clauses are generally NOT open source.

**Comment by benwiley4000** [comment]
Do you want devs to release source for their games or not? It's one thing to say "it would be cool for folks who contribute to the community through modding to be able to receive compensation for their labor" but another thing to come out and demand that the creator switches to a license that allows commercial reproductions. It sounds insanely entitled.

**Comment by coderbot16** [comment]
We don't necessarily want them to release the code under a license allowing commercial use. We just don't want the term *open source* to be used for something that doesn't conform to the OSI definition.

**Comment by benwiley4000** [comment]
The maintainers stated in the very first reply to this thread that misused the term and they would scrub any references to "open source" so as not to stoke the mob. Any yet the mob persists.

**Comment by coderbot16** [comment]
> mob

There are 12 total participants in this thread.

**Comment by purpleidea** [comment]
> Any yet the mob persists.

I opened the issue to help the author of the code in case they weren't familiar with the benefits of using a real open source license. I don't know about any mob, but I guess being helpful isn't appreciated when you see all the downvote fingers on my original top comment. Oh well :/

**Comment by benwiley4000** [comment]
My intent wasn't to be unnecessarily mean, sorry if it came across this way.. it's just assuming a lot when you presume the author's don't understand the implications of the license they chose or that they need to be schooled on how "open source really works." As an open source developer and maintainer and also as a game developer I can empathize with your desire to help folks learn about open source and I can also imagine that the folks who decided to blow the lid on this game's source code aren't totally excited to have folks coming and demanding more now that they decided to give something out for free. I realize that when I use the term "demanding" it doesn't line up with how you perceive your comments. It's the general tone of the folks commenting here in advocacy of an OSI-approved license that leaves the impression they aren't here to take no for an answer. "Sorry we're not gonna do that" is being met with "ah, you must not understand what you're talking about" (paraphrased).

**Comment by dos1** [comment]
There is a perspective of authors having "folks coming and demanding more now", sure. But there is also a perspective of someone lured by "it's open source now" tweet, screaming "awesome!" and already imagining all the amazing implications of that, just to read the details and be disappointed, because of that one tiny detail in the license preventing all those dreams from getting true.

...which BTW describes me and my initial reaction of "whoa, awesome, will port VVVVVV to Librem 5 and put it into PureOS!" - which turns out to not be possible due to incompatible license. Terry is free to use any license he wants, but... well, yeah... bummer.

This is why precise wording matters ;)

**Comment by benwiley4000** [comment]
Lol yeah I mean I can definitely understand that perspective. Likewise I hope you can understand most game developers are doing this (or trying to do this) as their main source of income whereas most open source software developers tend to have stable employment and a steady source of income which allows them to give away software for free without major restriction. I hope we see more games releasing their source.. and if they have "real open source licenses," awesome, but I'm happy with this sort of thing too.

**Comment by leilei-** [comment]
It's great that VVVVVV's code is out there.     Nobody's obligated to perfectly comply with RMS's ideals for any public release of text files that have functions and headers in them. 

Bring on the mods, fixes and ports!!! :)

**Comment by vanfanel** [comment]
Its SO great that VVVVVV is not open source! I am building a Raspberry Pi version right now! Having it depending only on SDL2 and SDL2_Mixer allows this, and since we have a KMS/DRM backend on SDL2, VVVVVV will run without X when building finishes here. Thats SO sweet!

However, I would love to see it included in Debian repos, for example, or OpenRisc OS, or ported to crazy platforms like the Amiga and distributed with AROS (the opensource and free Amiga OS implementation), or included with PureOS, just imagine.
So... Going GPL would be great! I highly encourage the authors to rethink license, too. Its not about RMS "purity", but about possibilities and reaching a greater audience :)

**Comment by Wuzzy2** [comment]
Quote from LICENSE.md:

> You may not alter or redistribute this software in any manner that is primarily intended for or directed toward commercial advantage or private monetary compensation. This includes, but is not limited to, selling altered or unaltered versions of this software, or including advertisements of any kind in altered or unaltered versions of this software.

I immediately notice this is quite broad and a little vague. This has the following implications:

* As an user, I would consider it to be legally extremely dangerous to share VVVVVV basically anywhere. The license says that doing anything for “financial gain” is forbidden, but this is very vague. Is a single banner on a website already a violation? We don't know. What if I post a copy on a commercial website I do not own? Also a violation? What when I have created a private website during my worktime / during my break? My worktime could count as “private monetary compensation” … There are probably a dozen of possibilities you could construct some weird commercial use. All of these are in danger of being sued by the copyright holder, and I think the copyright holder has good chances of winning almost all of them (Note: IANAL, but courts usually side with the copyright holder). Therefore, I consider this game as if its under full copyright. I advice any potential law-abiding people who want to share this game *anywhere* to first ask for permission from the copyright holder, simply because you cannot trust the license to protect you
* Because of this restriction, this game is out of reach in the default install of Debian and other GNU/Linux distributions. 
* It's a self-written license, so it's not tried-and-tested in courts. Any lawyer that is worth their salt will tell you you really shouldn't self-write your own software license because you don't know how it will actually function when it goes to court. Instead, software developers should use a well-known license because there will be fewer surprises. Copyright law is incredibly complex, and you do not want to deal with surprises (I hope!). *inb4 someone finds a loophole in your license and abuses it only to troll you* :D

I will not dictate your ultimate decision on this topic, but I have written this post in hope you will make an informed decision. I will hope you side with the community and freedom, but I will in no way make demands.

**Comment by flibitijibibo** [comment]
Wanted to see how this thread ran for ~24 hours, and I think it's about run its course... I thought about posting a more verbose opinion from myself on the subject, but the impression I get is that my opinion won't actually matter to anyone (it usually doesn't), so I'll skip that and lay down the framework for future license concerns:

First and foremost, **the license isn't going anywhere, end of story**. The goal is for the source to be readable by the public, and for the people who really like VVVVVV to fix things if they want. This isn't a revenue generator, this isn't required for customers to enjoy the game, and this isn't something that game developers think is necessary. They also don't care if they're wrong about any of those things. **Any further requests to change the license will be closed, repeat offenders will likely be flagged/reported.**

The use of "open source" was a bad idea, so we're doing our best to remove that phrase. Reports like #44 are fine. We also acknowledge that, given that we have a custom license, that there are bound to be *legitimate* bugs like #8, so reports like those are fine too. Lastly, there has been a request for a more rigorous CLA system (#42), so we'll take feedback on that as well.

We're up for making minor fixes to our existing system, as this is new territory (both in that indies basically never release source code, and there isn't much precedence for a good license for a project like this, particularly one that is actively trying to centralize active development instead of dumping a zip file and saying "get lost" like every other developer has historically done). But that's about as far as it's going to go. If you want to contribute to proper Free Software gaming projects, consider [one](https://github.com/FNA-XNA/FNA) [of](https://github.com/FNA-XNA/FAudio/tree/master) [the](https://github.com/FNA-XNA/MojoShader/tree/fna) [many](https://github.com/flibitijibibo/SDL2-CS/tree/master) [projects](https://github.com/FNA-XNA/Theorafile/tree/2eab88940091765c27bdeaad87d25d2fd181f456) [I](https://github.com/flibitijibibo/MonoKickstart) [have](https://github.com/flibitijibibo/FMOD_SDL) [maintained](https://github.com/wine-mirror/wine/tree/master/dlls/xaudio2_7) [and](https://hg.libsdl.org/SDL/) [patched](https://github.com/google/angle) over the many years I have spent on Linux games.
