### ISSUE TITLE
Getting Victoria's trinket causes all music to stop

### ISSUE THREAD

**Issue by mcpower** [TerryCavanagh/VVVVVV#712]
Can restore the music by switching focus to another program then switching back, reloading the save file or (presumably) starting a new music track.

https://user-images.githubusercontent.com/6015058/114290082-48295a00-9ac0-11eb-8aae-a5d0dcbdcc67.mp4

**Comment by flibitijibibo** [comment]
More stuff in the #701 pile... really want to replace SDL_mixer with FAudio when this tag is done.

**Comment by flibitijibibo** [comment]
Huh, this looks suspicious... https://github.com/TerryCavanagh/VVVVVV/blob/master/desktop_version/src/Scripts.cpp#L5472

**Comment by InfoTeddy** [comment]
Yeah, it looks like the previous behavior relied on `music.play(4)` (via `trinketscriptmusic`) to start the music up again after a `music.haltdasmusik`. `musicfadein` wasn't implemented before 2.3.

My guess as to what's happening here is that `music.play` simply can't start the music back up again if mixer is currently paused. I would expect mixer to start playing music again when `Mix_PlayMusic` gets called, but I guess from the point of view of mixer's designer, it would be understandable if they intended it so that attempting to play music while music is paused does nothing... That only raises the question of what, exactly, we should do to work around that - I'm guessing just a

```c++
if (Mix_PausedMusic())
{
    resume();
}
```

?

**Comment by flibitijibibo** [comment]
Yeah, that would be my solution. Pretty much every sound API I've ever used treats it that way, so may as well follow along...

**Comment by InfoTeddy** [comment]
Alright. I just thought of something better. `resume` should be changed to

```c++
if (Mix_PausedMusic() == 1)
{
    Mix_ResumeMusic();
}
```

Then we can just call `resume` without worrying about whether the caller should add the check or not.

**Comment by flibitijibibo** [comment]
Makes sense to me - as long as it reintroduces compatibility I can merge it in, either one is possible AFAIK.
