### ISSUE TITLE
2.3 Beta Branch Save Errors

### ISSUE THREAD

**Issue by bcmccracken** [TerryCavanagh/VVVVVV#713]
Hi there, 

I installed the 2.3 beta branch from scratch (I've only ever played on other platforms, but I own a Steam copy too!) and kept getting the new save errors. However, after switching to production/2.2, I was able to save, then switch to the 2.3 beta and continue and update that save without error. So it seems it's an issue with creating the folder or something else with first-time saving. Added evidence on this front: I renamed the Documents/VVVVVV folder (to _VVVVVV), loaded 2.3 beta and encountered the errors again, then restored the folder and had no trouble saving.

Excited to play this in 60fps! Y'all rock :)

**Comment by InfoTeddy** [comment]
From a cursory glance at the save data migration code, I noticed that 2.3 checks if both `saves/` and `levels/` already exists, but 2.2 only checks for `levels/`. Which seems a bit weird to me. Additionally, we should actually probably *directly* check if the directories already exist instead of relying on if mkdir returned an error to infer if they exist or not. I'm not sure if these have to do with the bug you encountered, but they're probably good things to look into.

> Excited to play this in 60fps! Y'all rock :)

I did the 30+ FPS, and thanks!

**Comment by flibitijibibo** [comment]
The main difference between 2.2 and 2.3 is that I explicitly made the directories with the OS mkdir, we eventually moved to physfs for that. That is almost certainly the cause of the regression.

**Comment by flibitijibibo** [comment]
I just rolled it back to my old mkdir logic:

https://github.com/TerryCavanagh/VVVVVV/commit/2f0a0bce4c663b7df2ed229ef897dcf3fd878ec6

PhysFS was introducing points of failure that I don't want to think about, so this just goes back to what 2.2 does, which we know works correctly.

**Comment by InfoTeddy** [comment]
I think the reason why 2.2 didn't check for `saves/` is because the 2.0 folder structure already had a `saves/` directly.

I'm still a bit uneasy about relying on mkdir erroring to infer that the folder(s) exist... is there a way we can check that the folders exist directly?

https://github.com/TerryCavanagh/VVVVVV/blob/2f0a0bce4c663b7df2ed229ef897dcf3fd878ec6/desktop_version/src/FileSystemUtils.cpp#L87

This should be `0777`. What you have entered here is actually `01411`.

**Comment by flibitijibibo** [comment]
Fixed the missing 0.

[mkdir](https://pubs.opengroup.org/onlinepubs/009696699/functions/mkdir.html)/[CreateDirectoryA](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createdirectorya) explicitly include stat checks, mkdir will return `EEXIST` and CreateDirectoryA will return `ERROR_ALREADY_EXISTS`.

**Comment by InfoTeddy** [comment]
Okay, that's good to know.

I think what we should do if the directory doesn't exist but there's an error creating the directory is just bail. Otherwise it seems like that could lead to bad stuff. But that's something separate.

**Comment by flibitijibibo** [comment]
New builds are up on Steam. @bcmccracken, does the latest fix this?

**Comment by flibitijibibo** [comment]
Did some local testing and can verify that this was Windows-only, which is probably why it took so long to notice. My patch combined with Dav's fix took care of this as far as I can tell.
