### ISSUE TITLE
Credits scroll in over-30 mode is not interpolated

### ISSUE THREAD

**Issue by mcpower** [TerryCavanagh/VVVVVV#715]
(This is an extremely small nitpick, feel free to close if it's too minor of an issue)

The post-game credits scroll in over-30 mode is rendered at 30 FPS without interpolation. It's barely noticeable, but becomes more apparent when you have a high refresh rate monitor.

**Comment by flibitijibibo** [comment]
I think this is just an increment in Render, probably can just use real time updates and ignore fixed updates entirely. Won't require it for 2.3 but it should be easy enough.

**Comment by InfoTeddy** [comment]
Huh? I'm pretty sure this is interpolated.

**Comment by InfoTeddy** [comment]
On further investigation, it looks like the credits scroll at 1 pixel per frame, which is basically impossible to interpolate because we only use integer coordinates. If you press ACTION, the sped-up credits is interpolated.

> probably can just use real time updates and ignore fixed updates entirely.

I don't like this because I'd like to keep it the same speed regardless of framerate.

**Comment by flibitijibibo** [comment]
Ah crap, was worried it might be single-pixel scrolling. Yeah, sadly we can't do much about this because we can't do subpixel rendering (not without it looking unspeakably ugly, especially for text).

Sadly this is `WONTFIX` but only because pixels are no fun.
