### ISSUE TITLE
It's possible to open the map during a teleport

### ISSUE THREAD

**Issue by liquidev** [TerryCavanagh/VVVVVV#736]
On 2.3-testing it seems to be possible to open the map while the teleport animation is playing. This threw me off the first time I noticed this, as I tend to spam Y on the controller to activate teleporters as fast as possible.

**Comment by InfoTeddy** [comment]
Works as intended.

**Comment by flibitijibibo** [comment]
I don't know if we'll be able to cover this for 2.3, but we'll absolutely be able to fix this for 2.4 - the main goal of the input refactor will be splitting up the bindings to be individual actions rather than dumping a whole bunch onto a single key - making actions like map and pause unique bindings is a top priority for that work.

**Comment by InfoTeddy** [comment]
Agreed, the bindings should be separate - but this is the wrong issue for that, and puts too much focus on being able to open the map rather than the fact that the bindings aren't separate. We should make a separate input bindings issue instead.

**Comment by flibitijibibo** [comment]
Once 2.3 is out I'll make a couple meta-issues for both input and audio - this will just be an issue under the Mega Input Umbrella. There are probably a lot of things we'll have to double check because the bindings get into the weeds in a few places, so having these as test cases will be helpful.
