### ISSUE TITLE
Steam achievements not working

### ISSUE THREAD

**Issue by Fractodacto** [TerryCavanagh/VVVVVV#757]
Hi, I played on the new beta and I got 11:53 on the super gravitron but I did not get the 10 second steam achievement. However, the trophy still shows up in the secret lab. As soon as I reverted back to 2.2, the achievement showed up.

**Comment by flibitijibibo** [comment]
Excellent catch - as it turns out the beta is using the unofficial build flag which disables achievements (for obvious reasons), but the official build will enable Steamworks. The networking functionality is unchanged from 2.2 so it'll work as expected when the final release is out; when you ran 2.2 it picked up on the flag that 2.3 set and made the Steamworks API call for us.

Thanks for checking this out!

**Comment by Fractodacto** [comment]
ohh thanks! can't wait for release!

**Comment by InfoTeddy** [comment]
> although I couldn't pick up on what the obvious reasons are for it disabling achievements

(This was edited in... why doesn't GitHub notify you of edits? :angry:)

Presumably, in case there's a bug in the beta that ends up unlocking achievements.
