### ISSUE TITLE
Softlock with terminal revealing map rooms

### ISSUE THREAD

**Issue by Calneideck** [TerryCavanagh/VVVVVV#833]
![20210901211331_1](https://user-images.githubusercontent.com/10572099/131662701-f19082a9-8444-4673-af5b-89af37caa39e.jpg)

The game soft locked after opening the terminal on this screen. It highlighted the green area but then there was no way to close it.

Had to quit and return to menu.

----------

Platform: PC (Windows 10)
Store: Steam
Version: 2.3

**Comment by flibitijibibo** [comment]
@InfoTeddy, are you able to take a look? Going to tag FNA first, so you have some time here...

@Calneideck, if you still have the save files those will help a lot in reproducing this quickly.

**Comment by flibitijibibo** [comment]
I wasn't able to reproduce this locally... hitting Space (or A) was enough to make it go away.

**Comment by InfoTeddy** [comment]
I am unable to reproduce this. We need more information.

**Comment by InfoTeddy** [comment]
On Windows, `Documents\VVVVVV` in your user directory. On macOS, `~/Library/Application Support/VVVVVV/`. On Linux, `~/.local/share/VVVVVV`. Once you find the `VVVVVV/` folder, the save files will be `tsave.vvv` and `qsave.vvv` in the `saves/` subdirectory.

**Comment by InfoTeddy** [comment]
Okay, so, opening the map screen while the teleporter screen is being brought down ends up getting you stuck on the teleporter screen. This is the most plausible explanation for what happened here. Meaning, I'm pretty sure active user input is required to softlock in this state.

Since this seems to be caused by user input, it's a bit of a lower priority for me, so I'm going to go sleep and end up fixing this in the morning.
