### ISSUE TITLE
#609 causes regression letting player flip during cutscenes

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#839]
It's not even been a day and 2.4 already has a regression!

This time, the player is now able to flip during cutscenes thanks to #609 being merged. Specifically, cutscenes that are completely gamestate-based, such as teleporter cutscenes and Level Complete. `git bisect` points to 1eb8570329ec50aac4cb5c772ae71206fd48ff13 being the cause.

**Comment by flibitijibibo** [comment]
Thankfully this one looks pretty straightforward... I think we just have to roll back the part that specifically deals with the input actions, but I don't know what other effects that would have.

**Comment by InfoTeddy** [comment]
Another thing revealed during testing is that #609 also makes it so the mid-air flip mechanic (trapping a duplicate player entity so the true player is always eligible to flip) immediately pushes Viridian in the opposite vertical direction (due to the burst of momentum), instead of changing their direction smoothly like they had just touched a gravity line (or even flip token).

I'm not sure how to feel about this; the behavior seems radically different than previously, along with the fact that some level might be designed without the expectation of you flipping in mid-air so sharply, so this would end up making existing mid-air flip levels easier or harder. Considering just reverting the whole thing...

**Comment by flibitijibibo** [comment]
That seems like a pretty serious userspace breakage, but at the same time I don't want to _totally_ revert it - the patchset had a legitimate purpose and it made sense to both of us who reviewed it, so there may be some way to nudge this changeset in the right direction (as is the case with a lot of VVV fixes, honestly).

I'll boil it down to this: @leo60228, if you think you can nudge it in the right direction, go for it, otherwise we can just back this out and try the idea again later - no hard deadline on this since we now have a comfortable stable branch for most people to work with.

**Comment by leo60228** [comment]
I think that this could be solved by both fixing the regression and making it so that the momentum boost no longer applies if flipping in midair. I'm not 100% sure how to implement that at the moment, though.
