### ISSUE TITLE
Return key may stop working after teleporting

### ISSUE THREAD

**Issue by dsalt** [TerryCavanagh/VVVVVV#841]
Teleporting to an unnamed room works fine.

Teleporting to a named room breaks things.

I haven't (yet) been able to test whether returning to an unnamed room ‘fixes’ this.

Bisection points at 82971296c2e220198a5c391f1e9c6a4dd9426789.

I altered the code slightly:
```diff
diff --git a/desktop_version/src/Game.cpp b/desktop_version/src/Game.cpp
index b63d59c..e0fe945 100644
--- a/desktop_version/src/Game.cpp
+++ b/desktop_version/src/Game.cpp
@@ -6894,6 +6894,7 @@ void Game::unlockAchievement(const char *name) {
 
 void Game::mapmenuchange(const int newgamestate, const bool user_initiated)
 {
+printf("mapmenuchange: %d %d %d\n", user_initiated, graphics.menuoffset, map.extrarow ? 230 : 240);
     if (user_initiated
     && graphics.menuoffset > 0
     && graphics.menuoffset < (map.extrarow ? 230 : 240))
```
and, once the bug was triggered, saw the following output consistently when trying to open the map:
```
mapmenuchange: 1 230 240
```
(This particular set of values did not occur otherwise.)

I suspect some bug elsewhere involving `map.extrarow`.

**Comment by InfoTeddy** [comment]
Thanks for the bisect! Honestly I feel like we should ditch `map.extrarow`, last time I reviewed it it was of basically no consequence (the map animation still takes the same amount of time either way; room transition thresholds do not depend on it in any way) and basically made the code more error-prone.

**Comment by InfoTeddy** [comment]
Ok re-reading your message... I think the problem here is `graphics.menuoffset` instead? Because it shouldn't be 1 here, it should be basically 0. But I'm taking a look at this more in-depth now.

**Comment by InfoTeddy** [comment]
No, I misread, that 1 is the value of `user_initiated`.

**Comment by dsalt** [comment]
Log text (with `⇒` added location info):
```
⇒ Philadephia Experiment
Game saved
mapmenuchange: 1 0 240
mapmenuchange: 1 240 240
Game saved
Game saved
⇒ warped back to the ship
mapmenuchange: 1 240 230
Game saved
mapmenuchange: 1 230 230
Game saved
Game saved
⇒ Entanglement Generator
mapmenuchange: 1 230 240
```

**Comment by InfoTeddy** [comment]
Yeah, so, the problem here is definitely `map.extrarow` and us having to do all these weird gymnastics to make sure that when it's 1, `graphics.menuoffset` is 230 in rooms with room names, but if it's 0, `graphics.menuoffset` is 240 in rooms without room names.

Now it turns out I got the ternary the wrong way round (both in `mapmenuchange` and `maprenderfixed`), but regardless of which way it is, there's still a bug. As of now it's `map.extrarow ? 230 : 240`. So if you get `graphics.menuoffset` to be 230 because you closed the menu in a room with `map.extrarow`, then you can't open the menu in rooms with room names because 230 is less than 240.

But if it's the right way around, and it becomes `map.extrarow ? 240 : 230`, then the bug happens the other way around. Closing the menu in a room with a room name will make it so you can't open the menu in a room without a room name, because 230 is less than 240.

Hence my sentiment that we should just drop this `map.extrarow` business and stop all these headaches about it...
