### ISSUE TITLE
In control tutorial prompts, the actual key to press should be shown

### ISSUE THREAD

**Issue by python-b5** [TerryCavanagh/VVVVVV#846]
Currently the game gives the catch-all key name on button tutorial prompts (like "Press ACTION to flip"), but these are unintuitive and should be replaced with the actual key to press (so "Press Space, Z, or V to flip" or "Press A to flip", for example). It can pick between controller and keyboard inputs to show depending on what one was last used.

I started on a pull request for this but wanted to check if it's worth working on/would be accepted

**Comment by flibitijibibo** [comment]
It'll get blown apart by #834, focus on that and the strings will come next.

**Comment by InfoTeddy** [comment]
ACTION is already explained when you start the game. It says `ACTION = Space, Z, or V`. @TerryCavanagh has stated previously that he wants to keep the control scheme somewhat simple; it wouldn't surprise me if he had a reason for saying "ACTION" instead of "Space, Z, or V" in the tutorial.

Other than that, this is the ten millionth "we want input rebinding" report, and this is the ten millionth "2.4 will have input rebinding" response.

**Comment by TerryCavanagh** [comment]
Yeah, press ACTION to flip is fine as is.
