### ISSUE TITLE
Hide username in level folder path

### ISSUE THREAD

**Issue by notroid5** [TerryCavanagh/VVVVVV#853]
First of all, thanks to everyone for the updates!

However, under the new "Levels" option, you can see the person's username.
There are people that stream this game and not everyone wants their username to be known, no matter what kinda name one chooses.

So please think about an alternative (maybe use an environment variable in the path?) or at least do NOT just show this without an opt-in.

**Comment by InfoTeddy** [comment]
I might just make this an opt-in. Trying to detect any usernames or sensitive information in the path kind of runs into trouble when you consider 2.3 letting people run the game from any `-basedir` of their own choosing.

**Comment by Dav999-v** [comment]
I personally wouldn't be opposed to just removing the path display altogeher, and replacing it by something like this:

![Yeah, I replaced "open level folder" with "open levels folder" for extra clarity](https://user-images.githubusercontent.com/44736680/142657588-6ee25f43-4292-4825-a373-0d08e4089fd9.png)

The menu option to open your levels folder nearly always works - I remember it being added in 2.1 and removed in 2.2 because it probably didn't work everywhere or something - but right now it's apparently always available except in "tenfoot" mode. And even if it's not available, it could always just lead to a separate screen which just gives you the path.

That separate screen could also show it in a much better way than how it's currently done, with duplicated code to arbitrarily cut the path at 40 and 80 characters, and it doesn't handle unicode:
```cpp
        std::string tempstring = FILESYSTEM_getUserLevelDirectory();
        if(tempstring.length()>80){
            graphics.Print( -1, 160, "To install new player levels, copy", tr, tg, tb, true);
            graphics.Print( -1, 170, "the .vvvvvv files to this folder:", tr, tg, tb, true);
            graphics.Print( 320-((tempstring.length()-80)*8), 190, tempstring.substr(0,tempstring.length()-80), tr, tg, tb);
            graphics.Print( 0, 200, tempstring.substr(tempstring.length()-80,40), tr, tg, tb);
            graphics.Print( 0, 210, tempstring.substr(tempstring.length()-40,40), tr, tg, tb);
        }else if(tempstring.length()>40){
            graphics.Print( -1, 170, "To install new player levels, copy", tr, tg, tb, true);
            graphics.Print( -1, 180, "the .vvvvvv files to this folder:", tr, tg, tb, true);
            graphics.Print( 320-((tempstring.length()-40)*8), 200, tempstring.substr(0,tempstring.length()-40), tr, tg, tb);
            graphics.Print( 0, 210, tempstring.substr(tempstring.length()-40,40), tr, tg, tb);
        }else{
            graphics.Print( -1, 180, "To install new player levels, copy", tr, tg, tb, true);
            graphics.Print( -1, 190, "the .vvvvvv files to this folder:", tr, tg, tb, true);
            graphics.Print( 320-(tempstring.length()*8), 210, tempstring, tr, tg, tb);
        }
```

**Comment by flibitijibibo** [comment]
Yeah, i removed it in 2.2 since it was OS-specific stuff and wasn't quite as polished as SDL_OpenURL ended up being.

The fallback makes sense to me, I would test this on something like SteamOS (rip off the install process in my .plan) where xdg-open may run but not produce an error.
