### ISSUE TITLE
Individual translation of graphics files

### ISSUE THREAD

**Issue by Fussmatte** [TerryCavanagh/VVVVVV#860]
This is maybe a bit far off, but I think it'd be worth considering the possibility that individual languages can choose to provide custom graphics. Something similar was done with the Nicalis Japanese ports to translate each enemy into Japanese (with debatable quality).

Here are some homemade mock-up examples showing translated enemies in action in various languages (graphics mine):
![image](https://user-images.githubusercontent.com/44736084/149843963-1e17d718-d8c7-45bf-8871-e6838a0c7652.png)

One issue that's been brought up with this is hitboxes: they're pixel-perfect in the game and changing an enemy graphic even a little could muss it up. Misa's suggested solution was to load hitboxes with the original graphics but render enemies with another.

Another is whether this is necessary or worth it at all — I personally think having the option is nicer than not (for example, I think it may help contextualise room names better), but others might (and do) feel differently, that it's rather superfluous and isn't a big deal for most players (which it probably isn't).

What are your thoughts?

**Comment by InfoTeddy** [comment]
> One issue that's been brought up with this is hitboxes: they're pixel-perfect in the game and changing an enemy graphic even a little could muss it up.

Specifically, since the hitboxes are pixel-dependent, changing the graphics literally means changing version compatibility. This has already happened once; in 2.0, transparent pixels were counted as existing if they were colored non-black, while in 2.2 fully transparent pixels are never counted as existing, but due to a bug with the masking code, the red channel of a pixel (assuming it isn't fully transparent) is checked instead of the alpha channel. (I've used this in a level.) I have a couple TASes dependent on sprite pixels and I'm pretty sure the RTA speedrunners have a couple routes or runs based on sprite dependency too.

Fortunately, this _only applies_ to sprites that are 32x32 or less in size; bigger sprites use a completely rectangular hitbox that isn't dependent on their pixels (these are the Maverick Bus, TRUTHs, ZZT centipedes, and the emitter in The Solution is Dilution).

I'd love to fully ditch sprite dependency but that would obviously be a huge breaking change. On the other hand, people might ask why the PC/mobile localizations don't change their sprites (I know I would), and I'd hate to pass up an opportunity to be better than Nicalis (as discussed in the VVVVVV server, the Japanese translation is already of questionable quality and the sprite changes they did even moreso) - though we're already doing quite well compared to them.

So I feel like using the hitboxes of the original graphics while simply drawing a different sprite is a reasonable solution.

**Comment by Dav999-v** [comment]
So, I'm not entirely sure about this, and I'm not adding it to my personal localization todo list; but I can see how it makes sense. Drawing the translated graphics while using the original sprites for collision detection is what I would go with as well.

**Comment by Fussmatte** [comment]
I should also note that this wouldn't only apply to enemy graphics, but would allow translation of the Level/Game Complete graphics. This would probably benefit some languages like Japanese, where the text from the main font may be too thin to look nice in a large graphic like this:
![image](https://user-images.githubusercontent.com/44736084/149674858-3d89bbb4-05d0-426f-8b54-90ad25110ce5.png)
![image](https://user-images.githubusercontent.com/44736084/149674863-a7f42fa4-a2ad-463f-a900-01cc79fb3318.png)
(**Top:** k8x12; **Bottom:** custom graphic.)

**Comment by mothbeanie** [comment]
this came up in a discussion on discord about localizing the icons for the map legend. instead of localizing the "S" (trinket) and "T" (teleporter) icons for every language, we could have a set of universal representative icons (see below) which Terry said that he liked and that it wouldn't be a big deal to just use these for 2.4 onward.

![tiles](https://github.com/TerryCavanagh/VVVVVV/assets/19874772/93394436-b8c3-4b0f-89d7-85cdc1ba747a)
tiles.png with the new icons
![tiles_legend](https://github.com/TerryCavanagh/VVVVVV/assets/19874772/d38b53c7-4d6b-4cc1-b0d7-2eeb3d8a714a)
icons only as an overlay
![use case](https://github.com/TerryCavanagh/VVVVVV/assets/19874772/6613d298-8fee-4ef5-bfed-36146d6666dc)
example of them in use

i wanted to put them here for posterity, but also just some thoughts on how to proceed:
 - if we use these, we don't have to localize the map legend at all - only the sprites will be individually localized
 - we could include a menu option to let players toggle between the new icons, and the old ones (which would be S and T regardless of language)
 - we could localize the map legend anyway, and then if the setting is turned off, players would see letter icons in their own language. this would be the most amount of work and possibly not worth the trouble

**Comment by InfoTeddy** [comment]
Removed the 'required for 2.5' tag (so now this is required for 2.4 by default) as discussion in the Discord has revealed we do want to do this in 2.4.

**Comment by InfoTeddy** [comment]
> So if anybody objects, speak up now!

I have none as long as we don't have to update `data.zip` again.

**Comment by Daaaav** [comment]
My main worry is that it might be a bigger change than it seems from the technical and file management side. But this would probably have technical advantages too (not needing to worry about both a localizable 32x32 sprites.png as well as a localizable 8x8 tiles.png for example), and it'd probably be worth it for the other reasons, so let's think through our options here. :)

To recap, `data.zip` is locked down, and the language files and fonts are added as separate folders inside the repo (for when the user compiles the game themselves) and copied _next to_ `data.zip` in distributed versions. (These should not be in a zip, because the fonts and especially the language files have to be modifiable by us as time goes on, have to be in sync with the code, and the game itself has translator options to modify the language files at runtime.)

So we need to make a decision for how to add this new map legend image, as well as other new graphics from now on:

- Should we do it this way: ["If we make changes or add new files we'll add new zip files"](https://github.com/TerryCavanagh/VVVVVV/issues/1006#issuecomment-1705437725)? We haven't yet started a chain of "You do not have data.zip, data2.zip or data3.zip!", and it'd probably be fine to go that route, but it seems kind of a waste to add a dedicated new zip for a single file.

- Or should we instead add any new graphics to the repo instead (just like the language files and fonts?)

I don't have the same question for the translated versions of the sprites (or of the oldschool S/T icons) because it makes sense to just have those bundled inside the language folders. But this new legend file is not tied to any language (including English).

**Comment by Daaaav** [comment]
(After a discussion on Discord, there's another option for the map legend that seems pretty reasonable and also allows us to postpone the definitive graphics file decision: add them as characters to the 8x8 font.)

Meanwhile: #1031

**Comment by TerryCavanagh** [comment]
Delighted to be able to say that this issue is now complete! So glad we did this for 2.4!
