### ISSUE TITLE
[Enhancement] Improving internal scripting

### ISSUE THREAD

**Issue by M0REKZ** [TerryCavanagh/VVVVVV#867]
(Sorry if bad english)

Hi, I just wanted to mention some improvements that would do very good to the internal scripting, otherwise the following things hurt level creation quite a bit (correct me if there is actually a solution or "trick" to solve these problems without much trouble, or if some already command ):

* Delay(): prevents the player from moving, which doesn't give much freedom when scripting... maybe a "delayscript" can be added to just pause the script without freezing the player.
* Do()-Loop: when you want to do "infinite" loops, one can just put a number like "9999999999999", but that's pretty inefficient, especially if you need _several_ loops at once, maybe can add an option to make "do loop" infinite without the need to add meganumbers?

These ones here are additions that are not so "essential" and could live without them, but they would be nice to have:

* ResetRoom?: instead of creating millions of gotoroom() scripts (which take up a lot of script space) for each room, you could just make a single script that restarts the room you're in.
* Sensor like system?: The scripts in a room can be used only 1 time until you reset the room, this hurts a bit if you want to do sensors, maybe if you can add something like "ifplayerposition(x1,y1,x2,y2,script)" inside of an infinite do loop, can do multiple sensor systems and a lot of special things
* Command for change Entities position? or at least for crewmates?, maybe something like "changexposition() changeyposition"?
* Command for change crewmates size? if add this, you can make more huge (or little) cremates with "changetile()", will be nice for character creating.

Thanks

**Comment by InfoTeddy** [comment]
I would also like to reiterate that what Ally said about these features definitely breaking forwards compatibility and going against Terry's wishes is correct. So don't be surprised if this issue gets closed.

That said, I'd personally want some sort of C modding API that'd be stable and let people do whatever they wanted with the game without having to touch the source code (being forced to use source code raises issues of distribution and having to keep up with upstream updates, etc.), alongside just not special-casing the main game or custom levels and making them the same thing in the backend. Because after all, having to download separate versions of the game (even if they're not official) is the ultimate slap to the face to forwards compatibility. Adding on extra scripting commands doesn't really make the game feel any less janky to make levels with because to a first approximation, the scripting language is absolute trash to work with and we'd be better off writing things in a proper language, like... any programming language that exists today, and thus having a C API for them to interface with.

**Comment by M0REKZ** [comment]
Wow... that remember me a little [SMBX ](https://wohlsoft.ru/pgewiki/Branches_of_Super_Mario_Bros._X),the situation is different, the project was abandoned, but the similar thing is that when people saw that certain features were missing, they started making a lot of different incompatible versions of the same game

**Comment by InfoTeddy** [comment]
Well, that's pretty horrifying. I definitely want to avoid that if at all possible with this game.

**Comment by TerryCavanagh** [comment]
Just to chime in here; I was really worried about breaking forward compatibility back in the 2.2 days, and I think it was probably the right call then. I guess I could possibly be convinced otherwise now, but it feels like it would be a shame at this point?

If the pandora's box of expanding scripting was to be opened, though, I'd probably want to literally start over, and just add support for a whole new type of scripting, with lua or something similar. The simplified scripting support in VVVVVV 2.0 was too basic for a lot of things that people ended up wanting to do, and internal scripting was never designed to be a publicly available interface.

**Comment by AllyTally** [comment]
Yep; that's why my suggestion contained "maybe the better option would be making a system aside from cutscene scripting to give levels more freedom and customizability on what they can modify about the game engine. " Taping new additions onto systems not made for those will produce some pretty scary code, and wouldn't be very easy for the user. Maybe a Lua API is our best bet? We did a lot of theorizing on one of those in the VVVVVV server for Community Edition, I'm sure we could pull something together?

**Comment by M0REKZ** [comment]
Well........ actually my main problem was caused by the fact that I can't (or couldn't) make an internal script call itself (you can in simplified script if you do 2 scripts), so if you want to keep everything as it is as it is, this problem could be solved, and I would be ready...  

Well, if you want.....................

...since this is apparently going to lua, so it's up to you :p

**Comment by Dav999-v** [comment]
I personally believe (and have brought up on Discord) that generally aiming for keeping forwards compatibility as a rule of thumb is still the right call to prevent feature creep - discussions about adding new features (like the `pdelay` thing, or even making the main game and custom levels the same thing and thus inherently moving to a new super-flexible custom level format) always make me fear for this brake coming off and VVVVVV losing its charm and changing for the worse because people add every feature they can.

I do not think of this as an absolute though, that's why I said "generally aiming for [...] as a rule of thumb"; and it also _hasn't_ been absolute thus far - more minor forwards-compatibility-breaking features have been added, but they're being done slowly and they're still carefully considered. I think this is a pretty good strategy, if new features are being added slowly enough and keep being carefully considered, VVVVVV can evolve while leaving everyone at ease.

**Comment by Dav999-v** [comment]
> Well........ actually my main problem was caused by the fact that I can't (or couldn't) make an internal script call itself (you can in simplified script if you do 2 scripts), so if you want to keep everything as it is as it is, this problem could be solved, and I would be ready...

@M0REKZ So I just tested this, and it is possible for an internal script to call itself, even with only one script - you just need to use `customiftrinkets` (otherwise you're trying to call a main-game script), or prefix the script name with `custom_`.

If this hadn't actually been possible yet though, allowing scripts to call themselves is the kind of change I would've been totally happy with, though. It's the kind of minor change that wouldn't result in a slippery slope that changes VVVVVV for the worse, while still potentially improving quality of life for level creators.

**Comment by flibitijibibo** [comment]
At least in my experience, having a policy that only adds features when it's overwhelmingly required is the best way for something that's already "finished" - FNA for example now only extends the XNA spec when:

1. There is physically no other way to implement something
2. Ignoring it would result in either a cert failure or a _very_ deep fracture in the community

When these two things happen together, a patch is usually already made, out in the wild, and widely in use, so it's just a matter of upstreaming it. If there are alternate methods to doing something that are already available, just use that, if cert doesn't need it and the community hasn't adopted it aggressively, no sense adding to the maintenance pile. Without those requirements you're only adding something because you _want_ to rather than _need_ to, which is fun for one-off prototypes but costly for a shipping product.

(But enough about the C++ spec, heyooo)

**Comment by M0REKZ** [comment]
well... thanks for the help, still it's unfortunate that can't at least add the pdelay()
