### ISSUE TITLE
[Question] Coop Support on the PC Release?

### ISSUE THREAD

**Issue by Fancy2209** [TerryCavanagh/VVVVVV#884]
Hello, I am sorry to bother or if this isn't the right place to ask, but has it been considered on implementing the Local Cooperative Mode that the Switch Version has? It would be really cool to be able to experience VVVVVV with a friend, but I don't own a Switch. This is why I am asking, also because I didn't see it on the 2.4 List.
This could also be cool since I am pretty sure Steam Remote Play Together could work

**Comment by Fancy2209** [comment]
> 

Oh I didn't even notice that the Switch port was Published by Nicalis
At least Terry still owns the rights to VVVVVV...

Still I think Co-op could at least be great for custom levels, I am sure people would love to do Custom Maps for 2 Players

**Comment by TerryCavanagh** [comment]
Yeah, I had nothing to do with the co-op mode in the Switch version of VVVVVV, Nicalis did that on their own. From what I've seen it basically works pretty well, though I would have done a few things differently! It's nothing something that I'm interested in adding to the game at this point, though (especially since I'd have to implement it as a new feature from scratch)
