### ISSUE TITLE
[question] a time limit clause in the license

### ISSUE THREAD

**Issue by pirate486743186** [TerryCavanagh/VVVVVV#888]
Yes, i saw the pined issue about the license. I think this is different.

Copyright terms are incredibly long. In the EU it's 75 years, in the US 95 years, in other places it's even worse and they are other complicating details. In the US, it will probably be extended soon, because some famous mouse is about to fall in the public domain.... And then very likely re-extended many times more after that....
https://www.youtube.com/watch?v=tk862BbjWx4

What if you put a clause, that the license changes to new terms at a given date? The new terms could be anything you want.

**Comment by flibitijibibo** [comment]
Not a lawyer myself, but:

- The license and agreements we have with contributors is already in place, so we'd need to round up everybody to re-sign authorizing a manually-declared expiration date
- I'm not aware of prior art where the license text bypassed the expiration dates established by federal/international law; if anything the change is just _made_ without any scheduling in the text itself, just within the organization (i.e. need time for audits, etc)
- Predicting dates for expiration is _hard_. Sure, it'd be cool to switch to zlib some day, but when is that day? 20 years? 30? It ends up _adding_ to the problem of expirations being way too long, because the only thing worse than expirations happening too late is when they happen too _soon_, because it's a one-way street: once it expires, you can't undo that. As a result the solution becomes extending the date more and more until you end up with basically the same problems that established law has.

As mentioned in the sticky, I would absolutely prefer a standardized permissive license, but adding complexity to the legal text isn't going to make that happen any faster than if we just wait for the right time to make the switch, and the existing text gives us the necessary room to make that switch without scheduling it ahead of time.
