### ISSUE TITLE
[minor] migrate settings to .config in linux

### ISSUE THREAD

**Issue by pirate486743186** [TerryCavanagh/VVVVVV#890]
it should be in $XDG_CONFIG_HOME/.config/VVVVVV
if the variable is empty then fallback to $HOME/.config/VVVVVV

**Comment by InfoTeddy** [comment]
Deferring to @flibitijibibo on this one. 2.0-to-2.2 save file migration was painful enough, I'm not sure if I want yet another path change since when giving people help I'd now have to ask people if they're using 2.3 or 2.4, or just tell them to check both paths. That's not to mention having to have save file migration code in yet again which was a source of bugs too if I remember correctly.

**Comment by flibitijibibo** [comment]
Yeah, we definitely can't change this again. We do at least follow XDG_DATA_HOME, which is usually what I default to when I can't do both at once (in VVV's case the save folder is a mount path, so we'd be mixing mount paths which is bad news for us).

Always good to check this, so it's definitely appreciated, but for this game we use DATA only rather than CONFIG.

**Comment by InfoTeddy** [comment]
> I had to search the internet to find it.

If the issue is that you couldn't easily find the path without searching the internet, then I feel like the best solution here is to just print the path in the options menu. It's what's already being done for player levels - which uses the same path, just one subfolder up. That path also has quality-of-life features like having an option to open the folder directly (via `SDL_OpenURL()`), added in 2.3, and in 2.4 the path is hidden behind a confirmation menu so streamers don't leak sensitive information.
