### ISSUE TITLE
Remove 50 line limit from text boxes

### ISSUE THREAD

**Issue by f-raZ0R** [TerryCavanagh/VVVVVV#913]
This is a somewhat arbitrary limit that just makes things more annoying. We have already removed all of the other arbitrary limits that just make things more annoying. It is thus, sensible to remove this one also.

**Comment by Dav999-v** [comment]
To be specific, the simplified commands `say` and `reply` have an arbitrary limit of 50 lines of text that they allow to be taken into the internal script representation:
```cpp
            int ti=help.Int(words[1].c_str());
            int nti = ti>=0 && ti<=50 ? ti : 1;
            for(int ti2=0; ti2<nti; ti2++){
                i++;
                if(INBOUNDS_VEC(i, lines)){
                    add(lines[i]);
                }
            }
```
Notably, when this limit kicks in, it completely breaks the script, unless the script was specifically written to be crushed in this specific way. Instead of copying 51 or more lines to the internal script representation, only the first line of text will be copied. But a `text` command with the full number of lines specified will still be added, thus making the text box eat further converted scripting instead of the text. I bet you could recreate the original 2.0 internal scripting exploit which abused `say(6)` that didn't work anymore since 2.1, just with longer textboxes, but I don't think anyone has been doing that.
