### ISSUE TITLE
graphical glitches on title screen and the tower

### ISSUE THREAD

**Issue by iliana** [TerryCavanagh/VVVVVV#927]
On 2ac85e6 I get graphical glitches like this on the title screen:

[<img src="https://user-images.githubusercontent.com/52814/220053859-22858770-b16e-4b5e-8777-c7cbacc241aa.png" width="50%">](https://user-images.githubusercontent.com/52814/220053859-22858770-b16e-4b5e-8777-c7cbacc241aa.png)

And the tower:

[<img src="https://user-images.githubusercontent.com/52814/220053672-9eabc06d-1c2c-4ab3-8ba8-86c45c9d4063.png" width="50%">](https://user-images.githubusercontent.com/52814/220053672-9eabc06d-1c2c-4ab3-8ba8-86c45c9d4063.png)

This is compiled for / running on Apple Silicon, which I am not sure will be supported for 2.4. If I can figure out how to cross-compile for Intel and run it I will update here.

**Comment by InfoTeddy** [comment]
What graphics backend is this using? GL, Vulkan, or Metal?

**Comment by InfoTeddy** [comment]
As for whether 2.4 will support Apple Silicon, that will be up to @flibitijibibo.

**Comment by InfoTeddy** [comment]
I see. It seems to me that the tower background for whatever reason is glitching on Metal. Possibly because it draws the texture on top of itself. We deliberately made sure it wouldn't draw with overlapping source and destination regions but I guess it's possible on Metal drawing the texture on itself at all is no bueno too.

The fix for this would be to use a temporary texture when scrolling textures instead.
