### ISSUE TITLE
60 FPS?

### ISSUE THREAD

**Issue by ClementineAccount** [TerryCavanagh/VVVVVV#99]
Would 60 fps be possible now?

**Comment by flibitijibibo** [comment]
No, someone still has to make the game run in a more accurate fixed timestep loop and then fix all the 33ms dependencies. So far we haven’t had any volunteers.

**Comment by TerryCavanagh** [comment]
This is possible, but it’s a lot more work than it appears at first. Reposting something I said about this on discord:

![97647D00-19F3-46FC-BD3F-1A8D55804B7C](https://user-images.githubusercontent.com/2874150/72682201-dcc62780-3aca-11ea-962d-844ee9c76b65.jpeg)

**Comment by InfoTeddy** [comment]
Someone actually [did make a 60 FPS patch](/Colon-D/VVVVVV-over-30-FPS).

That said, it takes the approach of keeping timestep the same, but then interpolating the animations. So basically, the animations are at 60 FPS but the game is still actually at 30 FPS. That said...

1. **The cutscene bar animations go by way too quickly.** My guess is that they're somehow based on deltatime now instead of amount of frames? Because if I run the mod under the TAS tool libTAS, it doesn't seem to happen... I'm really not sure what this guy did with them.

   This is an issue because the `untilbars()` command _directly depends_ on the animation of the cutscene bars. This means the timings of any script that uses cutscene bars are changed dramatically.

   Not only do the cutscene bars go by too quickly, the flash effect that makes the screen white _also_ goes by too quickly. What did this guy do with time management in this game?

   Speaking of running the mod under libTAS...

2. **If I run the mod under libTAS at 60 FPS fully (1000/17 FPS), libTAS can't advance time and the game is stuck.** But it works fine if I run it under 30 FPS (1000/34 FPS).

   I'm not sure what else to say. I have no idea what this guy did to the time management in VVVVVV, but I can't run the mod at 60 FPS in libTAS or else I'll never get past the "Press ACTION to start" screen.

3. **Somehow, you can't edge-flip off of a moving platform.** I didn't think this would be an issue, because edge-flipping off of regular tiles seems to be fine and untouched.

   Usually, you can flip off of a moving platform on the frame you leave it, but for some reason in this mod, you can't. This means that my Dimension Open Any% TAS desyncs with it, because at one point in the TAS Viridian edge-flips off of a moving platform.

There are more issues, but I think you get the gist of it.

**Comment by InfoTeddy** [comment]
The issues I've raised in the above comment have been fixed, so I've strikethroughed them all. Still, though, this issue should probably be closed because there already exists an over-30-FPS mod for the game.

**Comment by flibitijibibo** [comment]
Agreed, I think we’ve answered the original question... I would still be interested in upstreaming changes that keep the original logic stable while fixing frame time dependencies.
